### ISSUE TITLE
Cannot return null for view.

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#105]
This is a minor thing, but one which is counter-intuitive. I happen to have a view which can be switched off, so in that case I ~~have~~ had a view-function which just returns `null`. But that results in an error instead of being absorbed like `null` elements in a view:

    TypeError: d is null

It would be nice if views were consistent with their subparts in this respect.

The reason for returning `null` instead of suppressing the inclusion of the component in the parent is simply for a cleaner separation of concerns.

**Comment by leeoniya** [comment]
i don't think this can be done cleanly.  here's an outline of the internal process which may help explain why.

- render() returns a template that first gets passed through preProc()
- preProc() processes any *body* array, removing nulls, flattening nested arrays, creating vnodes from text strings, linking parent/child, setting vnode.idx's.
- after this is done, the body array is homogenized into a flat list of vnodes, and each vnode knows its position in parent via its vnode.idx. some vnodes can be simple placeholders for view definitions which have not been matched to the old vtree yet.
- now we match up the new preprocessed vtree to the old vtree. when a view def node is encountered and a view match is found in the old tree, it is moved into the new one, relinked into the new parent & idx and a simple redraw is called on it to produce the new subtree. the crux of the issue is that its render() cannot return null because that would require a re-flattening the parent body into which it was inserted, re-indexing of all its siblings.

one potential way around this is to not remove nulls at all but to skip them in all body iterators but this complicates and slows down a lot of ops in other perf-sensitive places.

your best bet is to either:

- vm.redraw() or vnode.patch() with {style: "display: none"}
- return the root node without a body
- avoid including the view in the parent

to me the last option is actually more obvious than what you're suggesting since looking at the parent is immediately obvious which views will actually exist at any point. much like the dom, the visibility of any element is a combination of its style properties & contents as well as its inclusion in the parent for which it can't be responsible.

Views are in fact consistent in that they must return a single root vnode. Speaking of which...

https://github.com/leeoniya/domvm/issues/106

**Comment by lawrence-dol** [comment]
Fair enough.

**Comment by leeoniya** [comment]
@lawrence-dol speaking of `null` in templates,  what are your thoughts on https://github.com/leeoniya/domvm/issues/104#issuecomment-264292975?
