### ISSUE TITLE
Provide a base `View` for ES6 classes to extend

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#109]
domvm should optionally provide some base `View` class that can be extended and consumed by `domvm.createView()`.

Like #108, this would make for a good isolated project, since it wouldn't require intricate familiarity with domvm's internals, the changes needed to accommodate this properly should be pretty shallow.

cc @grumpi, @yosbelms, @lawrence-dol

**Comment by leeoniya** [comment]
After toying around a bit with this (no pun intended), I've decided to leave it on the backburner.

One thing that emerged from the experiments is that I'll tweak the current API to map `this` in the view closure and in `render` to be the `vm`, rather than `vm.api`. There's a really high probability that this will allow for much more uniform ES6 class impls or ES5 prototype extending semantics in the future.

**Comment by lawrence-dol** [comment]
I agree with this being a separate project. In fact, I'd like to see a uniform place where we can deposit "code snippets" for DOMVM in a clean way, with an index, so people can see how others have solved problems without necessary designating them as officially being the "DOMVM way". I still want to provide my port for AJAX, but don't know where to put it.

Disclaimer: Personally, I dislike the psuedo-OOP of Javascript and prefer the functional encapsulation. And that's coming from someone who went from C to Java and though OOP was the best thing since the invention of the wheel. But, to be fair, it's mainly the lack of a syntactically-scoped `this`, and to a lessor extent, the lack of real encapsulation that makes me feel this way.

**Comment by leeoniya** [comment]
i pushed a WIP branch for this feature with a demo [1].

it turned out that doing the fully outside the lib wasn't possible, but the internal changes needed for the lib were fairly minimal. the functionality should be fairly complete, though it's probable that `injectView(vm)` still needs to handle ES6 view instances passed to it.

the parts that are needed internally in domvm are ES5 friendly, but the base class needs a minor boilerplate as seen in the demo, so it'll probably need to live outside to work in ES6 environments. i haven't tested the overhead of `isClass` testing, but it should be indistinguishable from noise except in benchmarks with thousands of sub-views. still needs a lot of testing, but the basics seem to work.

[1] https://rawgit.com/leeoniya/domvm/es6-class-views/demos/es6-class-views.html

**Comment by leeoniya** [comment]
this is now merged into dev with all core vm semantics working as expected. i dont think any special tests are needed for this since the provided boilerplate basically acts as if the base ES6 `View` class extends domvm's ViewModel.prototype, in effect giving the created view instance full vm powers. Everything else should Just Work (tm).
