### ISSUE TITLE
Select tag value

### ISSUE THREAD

**Issue by logaan** [leeoniya/domvm#114]
Is there any way to set the value of a select tag from the tag its self rather than setting selected on the child option tags?

I would like to be able to write:
```
el("select#kittens", {selected: "two"},
   [el("option", {value: "one"}, "one"),
    el("option", {value: "two"}, "two"),
    el("option", {value: "three"}, "three")])
```

Rather than:
```
el("select#kittens",
   [el("option", {value: "one"}, "one"),
    el("option", {value: "two", selected: true}, "two"),
    el("option", {value: "three"}, "three")])
```

If this is not possible currently is it a feature that you would consider adding to the domvm?

**Comment by iamjohnlong** [comment]
@logaan you could write a hook to do that https://jsfiddle.net/iamjohnlong/y89L60o5/ or write a custom select "component"

**Comment by leeoniya** [comment]
@logaan the DOM is a cruel mistress and doesnt always provide the most logical way to do stuff.

as @iamjohnlong suggests, the way to do this is with vnode-level `will/didInsert` lifecycle hooks attached through the attrs object: https://jsfiddle.net/tn41ka9L/

you can also use the view-level `will/didMount` hooks if you choose to componentize this sort of thing: https://jsfiddle.net/vvdsx5d1/

**Comment by leeoniya** [comment]
closing, but feel free to discuss further if needed

**Comment by tropperstyle** [comment]
Mithril will has a special case to handle this [1] - I think it is worth the developer convenience to support this in domvm. Thoughts @leeoniya ?

[1] https://github.com/MithrilJS/mithril.js/blob/ae27c0ff183da5c36c9bf0052567d9c2b8ae464c/render/render.js#L123

**Comment by lawrence-dol** [comment]
I think it looks useful; I've always thought that the absence of a "value" attribute on `select`, flagging instead the `option` is counter-intuitive and an obvious blunder. Of course it will probably make me add `value="..."` to `<select ...>` when working with normal HTML, but, oh well.

**Comment by leeoniya** [comment]
i was hoping this would suffice, and it mostly does, except for initial mount 😠: https://jsfiddle.net/740b3ja3/

i agree with @lawrence-dol that it'd be most logical with `value`. however, it would be a feature that'd be difficult to discover because HTML Doesn't Work Like That ™️.

given that `<option>`s cannot contain complex elements or even attributes other than value/selected, i'm tempted not to add anything and just have people use a helper function. it's not all that scary and doesnt impose a penalty across the whole lib:

```js
el("select#kittens", opts([
  el("option", {value: "one"}, "one"),
  el("option", {value: "two"}, "two"),
  el("option", {value: "three"}, "three")
], "two"))
```

`autofocus` is another one that could use special handling...and to mimic html would only need to work on initial root mount and not any view mount afterwards, though the latter may be more useful.

**Comment by tropperstyle** [comment]
> it would be a feature that'd be difficult to discover because HTML Doesn't Work Like That ™️.

Eh, I doubt most people are coming to domvm from vanilla HTML/JS/DOM. Most people are likely coming to domvm after trying React or Mithril. Given that both of these frameworks support this convenience, this is more the expectation of a commonly used element that leads someone to believe something is broken with domvm rather than it being an obscure "difficult to discover" feature.

**Comment by leeoniya** [comment]
> Eh, I doubt most people are coming to domvm from vanilla HTML/JS/DOM.

most likely come from jQuery since there are many more of them than the rest combined. this is part of the reason that the lib focuses on distributing a pre-built single file, staying small, tooling-free and as easy to get started with as jQuery.

i expect domvm's more sophisticated audience to be able to discern JSX-isms (`className="..."`), React-isms (synthetic camelcase events) and Mithril-isms (`withAttr`, etc.) from vanilla HTML/JS/DOM. i'm not particularly keen on imitating features from those by adding non-standard special cases unless the value is sufficiently high and does not introduce a perf overhead or add a bunch of extra internal machinery.

to implement this in domvm, i'd need to add handling in at least the hot `preProcBody()` and either mutate the attrs object of the parent to ensure it doesnt actually set a `selected` or `value` attrs on the `select` or add a bypass check to all the hot attrs loops. if the API was something closer to the more-explicit ivi, eg `h.select().attrs().children()`, then it would be easier to do without affecting perf lib-wide.

the value-added here isn't worth it IMO vs having a very simple helper.
