### ISSUE TITLE
Will/Did Mount Hooks do not fire for mount(elm,true);

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#120]
When you use the flag to overwrite the DOM element, the will/didMount hooks don't fire.

    domvm.createView(View).mount(elm,true);

Fiddle: https://jsfiddle.net/LawrenceDol/oL27ewow/2/

Change the flag to false and the hooks do fire.

**Comment by lawrence-dol** [comment]
Working on this, there's a fault, I think in:

    hook: function(hooks) {
        this.hooks = this.hooks || assignObj({}, this.hooks, hooks);
    },

To create or update the current hooks, as appears to be the intention, it should be:

        this.hooks = assignObj({}, this.hooks, hooks);

To replace the hooks, always, it should be:

        this.hooks = assignObj({}, hooks);

**Comment by lawrence-dol** [comment]
It appears the fault is in mount(), when the root tag is populated without being replaced:

        // if placeholder node doesnt match root tag
        if (el.nodeName.toLowerCase() != vm.node.tag) {
            hydrate(vm.node);
            insertBefore(el.parentNode, vm.node.el, el);
            el.parentNode.removeChild(el);
        }
        else
    ===>    { hydrate(vm.node, el); }

Hydrate does not call `fireHooks`. I fixed it by:

        else {
            vm && vm.hooks && fireHooks("willMount", vm);
            hydrate(vm.node, el);
            vm.hooks && fireHooks("didMount", vm);
        }

A work-around is to use a different tag name in the HTML, which forces the code down the `if` path, using `insertBefore`, instead of the `else` path.

**Comment by leeoniya** [comment]
good catch and thanks for the repro.

i'd like to solve this by just doing a no-op insert.

```js
else
    insertBefore(el.parentNode, hydrate(vm.node, el), el);
```
that should work, but currently gets tripped up by the `inDom` assertion [1] due to the element already being in the dom. this is the check that prevents hooks from firing when reordering sibling vm roots that are already mounted.

it would be easy to add another arg to `insertBefore` to bypass this, but i wonder if there's just a more robust check that can be done with the info already available.

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/src/view/dom.js#L91
