### ISSUE TITLE
are fragments worth keeping?

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#124]
fragments is a feature that's "neat" but i have personally never used or felt a need for.

since its implementation is non-trivial and must hook into internal functions it must be present in every build. this incurs perf overhead, code size and added complexity.

its benefits are but a few:

- a shallower dom in a few cases
- optimizing re-rendering of some adjacent subset of sibling nodes.
- allowing components that do not define their own root/wrapper. this is technically possible anyways by passing through whatever's needed to the child component via `opts`:
```js
function Parent() {
  return function() {
    return el("section", [
      vw(Child, null, null, {wrap: "p.foo"});
    ]);
  }
}

function Child(vm, model, key, opts) {
  return function() {
    return el(opts.wrap, "Hello World!");
  }
}
```

need to bench the perf gains and code size reduction from removing fragments.

**Comment by lawrence-dol** [comment]
I tend to agree with you. 

My only legitimate use case is the one where, in the process of building a table I want to return for some elements, three rows, a footer for a section, a header for the next section and the first detail row. That's, by definition, solvable by pre-processing the data into groups of rows (to use actual table groups) or by insertion of section-break dummy rows (to just emit rows).

So I am not strongly invested in this, though I do note that Mithril 1.x seems to have pulled this off. And I have no code that utilizes it as of yet, since the code where I need it is currently written for Mithril.

**Comment by leeoniya** [comment]
Mithril's implementation [1] seems rather different.

As mentioned in the original topic [2], domvm's fragment impl does not support lifecycle hooks. These hooks would be difficult to add because many hooks depend on actual DOM operations that happen at the very end of the redraw cycle. For instance, the only way will/did remove/unmount hooks are fired is when the DOM reconciliaton pass determines that the existing dom element is linked to an old/stale vtree [and was not recycled into the new vtree] and must be removed. Since fragments have no dom wrapper, there would have to be some complex assertion that *all* the fragment's children will be removed. Determining this in the current architecture is infeasable or requires a non-uniform additional pass over the old vtree that would check for what remains unrecycled and will be removed. This extra pass is expensive and there was a decent speedup after removing it from 1.x.

The other benefits listed in Mithril docs are that it's a clearer intent, which is subjective since you can always externalize a sub-template. The perf benefits may exist in Mithril, but fragments actually introduce perf overhead in domvm (which is already faster than Mithril).

Lifecycle methods *may* be useful, but I can't think of a concrete example when they would be required or even needed.

I know your original concern was the useless re-generation of the full body when only a a couple sibling nodes needed to be changed. Given that you now see how fast the view layer can be, perhaps this isnt that big a concern. If we're still talking about a table, having additional `tbody` wrappers isnt that awful unless you're going crazy with some shit UX that has 10k rows.

Is your Mithril app written in 1.x? Is there a plan to port it to domvm?

I would be interested to see what perf difference there is in Mithril 1.x w/fragments and domvm v2.x-dev with fragments removed and the app restructured a bit to use sub-templates and regenerate the full body or have `tbody` sub-views w/diff optimizations.

The build size difference is significant [1]. As is the reduction in code complexity. Benchmarks soon.

[1] http://mithril.js.org/fragment.html
[2] https://github.com/leeoniya/domvm/issues/106
[3] https://github.com/leeoniya/domvm/commit/8b18ace537bafe568f2dfe2add35a4e8ba553ef1?short_path=90524ff#diff-90524ffa151b37c8b277925c017ad1ba

**Comment by lawrence-dol** [comment]
To emphasize again, my need is, in my opinion, better addressed by restructuring the data. I support dropping fragments.

> your original concern was the useless re-generation of the full body when only a a couple sibling nodes needed to be changed

Actually no. My use case is that I have a table where a change in a significant field indicates the beginning of a new group; at that point I need to emit a footer, header and the detail row where the change was detected. But the row content generation is done with a per-row callback, so when the change is detected that call will need to return 3 rows instead of the usual 1 row. Since `table` has no (legal) arbitrary grouping of rows the only legal HTML I can emit (without restructuring the data into groups) involves putting every row into a `tbody` which is unnecessary bloat and semantically incorrect.

> Is your Mithril app written in 1.x? Is there a plan to port it to domvm?

Maybe. But maybe Mithril 2.0 first and then DOMVM. Unfortunately, at this point it's a business decision, not a technical one.

> I would be interested to see what perf difference

Just to be very clear, the need/choice is not for performance -- both Mithril and DOMVM are plenty "fast enough". It's purely a result of having an existing component which does all the heavy lifting for a complex and repetitive CRUD editor in the app and just calls on the app code to generate the row's cells. The classical "list of records with inline create, edit and delete operations".

**Comment by leeoniya** [comment]
it may interest you to know that this [1] is perfectly valid [2] html. so in actuality, you can have each record be a subview that can return *either* a `tr` or a `tbody`, which seems like it solves all cases of isolated redraw and no extra wrappers when not needed (row count = 1). honestly i didn't know this either till i tried it just now.

[1] https://gist.github.com/leeoniya/94f161dd4730d81331dce6e774ebca5d

[2] https://validator.w3.org/nu/?doc=https%3A%2F%2Frawgit.com%2Fleeoniya%2F94f161dd4730d81331dce6e774ebca5d%2Fraw%2F7c8d37d55dfd96040de4f1510e8999835f9c88c3%2Ftbody.html

**Comment by leeoniya** [comment]
here's a fiddle of this: https://jsfiddle.net/w4Lv8nm4/

**Comment by lawrence-dol** [comment]
That use case is tolerated by browsers, but flatly prohibited by the [HTML 5 spec](https://www.w3.org/TR/html5/tabular-data.html#the-tbody-element).

> 4.9.5 The tbody element
>
> ...
> 
> Contexts in which this element can be used:
> &nbsp;&nbsp;&nbsp;&nbsp;As a child of a table element, after any caption, colgroup, and thead elements, **but only if there are no tr elements that are children of the table element**.

**Comment by leeoniya** [comment]
something is really fishy.

how on earth does it validate then? (with every official/unofficial validator i could find online). They all test for improper nesting rules, so this fails:

https://gist.github.com/leeoniya/1f31df47de801a54c36e41a43bc17575
https://validator.w3.org/nu/?doc=https%3A%2F%2Frawgit.com%2Fleeoniya%2F1f31df47de801a54c36e41a43bc17575%2Fraw%2Fedc18f37cabe578fdd24de05a2f55149a41e3bec%2Ftbody.html

**Comment by leeoniya** [comment]
i guess the validators are too simplistic 😒 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody

**Comment by leeoniya** [comment]
> the only legal HTML I can emit (without restructuring the data into groups) involves putting every row into a tbody which is unnecessary bloat and semantically incorrect.

i would actually argue that semantically it *is* correct, with every record being a `tbody`.

there *is* a way to make the html both, legal and semantic. if each row does in fact represent a record or single entity, that a table is just one of many presentational rendering options. rather than using a `table` you can use ".record" with css `display: table`. you can do this using divs that have their css set to the appropriate presentational layout. by using divs, you now can have legal html by having both be adjacent without violating any html rules.

i've done the same in the past, and it works well when you need to collapse your "table" into a vertical non-table for mobile presentation within media queries. each table/tbody/tr/td has a specific css display type you can assign to arbitrary elements.
