### ISSUE TITLE
how to diff model when it is an object

### ISSUE THREAD

**Issue by xz64** [leeoniya/domvm#130]
Hi,

It seems that diffing of models is done on a strict equality basis. This means if you supply object literals to a view in a render function, `vm.redraw()` will update the DOM even though nothing changed. Aside from lifting the model object out of the render function, is there any way to prevent dom updating in this scenario?

Here is an example: https://jsfiddle.net/kkvfr972/3/
No matter how many times you click increment, the dom gets updated (even when nothing changed)

**Comment by leeoniya** [comment]
this needs to be better documented.

by default, views are keyed by the passed models. so `vw(View, model)` is implicitly `vw(View, model, model)`. if the view/key combo disappears between redraws, the view will get unmounted/recreated. since you're re-creating the wrapper passed into NumberView, this is what's going on.

You have 2 options, both of which require providing a static key that is persistent between redraws.

1. create a model wrapper that's persistent/static and mutate its `.number`
2. provide a third static key arg so it doesnt implicitly key by the wrapper
3. use a sub-template generating function rather than a sub-view

all of these will cause dom recycling

**Comment by xz64** [comment]
Thanks!

**Comment by leeoniya** [comment]
hey @xz64, does the new dom-recycling doc section [1] explain this concept adequately enough to have avoided the need to file this issue/question? also, do you think it's presented in a logical order with respect to the rest of the sections/examples?

thanks!

[1] https://github.com/leeoniya/domvm#dom-recycling

**Comment by xz64** [comment]
The explanation is clear. I think all the meaning of `(vm, model, key, opts)` should be explained closer to where it first mentioned, as a bullet list. (It is first mentioned after this section: "Views can accept an external" ) Having a `CONTRIBUTING.md` showing where to check before raising an issue would also be helpful.

**Comment by leeoniya** [comment]
>  I think all the meaning of `(vm, model, key, opts)` should be explained closer to where it first mentioned, as a bullet list.

wanna take a stab at it?

> Having a `CONTRIBUTING.md` showing where to check before raising an issue would also be helpful.

wouldn't the entirety of this file simply be "RTFM"?

**Comment by leeoniya** [comment]
i've also added a section that addresses sub-view vs sub-templating advice:

https://github.com/leeoniya/domvm#sub-views-vs-sub-templates

**Comment by xz64** [comment]
Yeah the` CONTRIBUTING.md` would basically be RTFM. Anyways if people open issues for things already stated in the README, it may indicate the documentation need to be more clear. I'll send you a PR for some README clarification.
