### ISSUE TITLE
SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by tropperstyle** [leeoniya/domvm#134]
https://jsfiddle.net/tcbwm7L1/

I assume the issue is that input[type=file] elements cannot be recycled, or at least Firefox 53.0.2 doesn't like it.

**Comment by iamjohnlong** [comment]
https://jsfiddle.net/tcbwm7L1/2/

Object notation works.

**Comment by leeoniya** [comment]
there are a several workarounds to this. in the end they all boil down to differently keying the vnodes to prevent them from being recycled: https://jsfiddle.net/tcbwm7L1/1/

a little-know fact (that will be documented soon) is that in the absence of a _key, vnodes will be auto-keyed by `_ref`, `_id`, or `name` [1].

> Object notation works.

wow, that's quite surprising and worth further investigation.

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/src/view/initElementNode.js#L42-L49

**Comment by leeoniya** [comment]
the problem here is order of assignment. if you try to set the value before the type is changed, it'll screw over.

with object notation it breaks too: https://jsfiddle.net/tcbwm7L1/3/

it's a side-effect of how selector-style attrs are merged into any provided attrs object. if explicit attrs exist, then that object is simply augmented with the additional attrs. i don't see a cheap way of avoiding this situation since it will still occur if you swap the order and define `el("input[value=#eee]", {type: "file"})`.

i think documenting that input/type recycling should be avoided by keying/id-ing/naming/_ref-ing inputs.

**Comment by tropperstyle** [comment]
> the problem here is order of assignment. if you try to set the value before the type is changed, it'll screw over.

So is there any argument to prioritize certain attributes in `patchAttrs`, or is `type` the only edge case?

**Comment by leeoniya** [comment]
> So is there any argument to prioritize certain attributes in `patchAttrs`, or is `type` the only edge case?

the roadblock is perf. `patchAttrs` is a very hot function, even adding a single condition to it will have a very noticeable impact on perf across the board, even when `type` is not present.

the entire attr patcher is a simple `for-in` loop over an merged attrs object. since there is no way to add hash keys at the beginning of an existing object, it's not something that can be done cheaply.

i'm sure there are other edge cases, but they will be equally difficult solve for the same reason. the universal solution is to just avoid recycling in each case - it doesn't even make sense to recycle certain types of inputs (text->number probably fine, radio->number probably not fine).

it's an unfortunate choice W3C made to have all input types with wildly different UIs and use-cases to be grouped under a single `input` tag.

**Comment by tropperstyle** [comment]
For what it is worth, my real use-case is much more complex than the boiled down jsfiddle. In the real code, it is not at all obvious that the input node would be recycled. 

I'd rather not develop the habit of adding `_key` by default, but I guess #135 would suffice with a warning when a collision does happen.

**Comment by leeoniya** [comment]
> I'd rather not develop the habit of adding `_key` by default,

it may not be terrible to get in the habit of adding a semantic `input[name=...]` in by default, though. this input-reuse case is the precise reason i added the auto-keying behavior for attrs that could reasonably be expected to be unique among sibling nodes.

it's a difficult/expensive problem to solve at runtime in non-compiled [and not statically analyzable] libs.

**Comment by tropperstyle** [comment]
Haha, I literally just finished adding `name` to all my inputs. I'm satisfied!
