### ISSUE TITLE
Inconsistent "this" inside object returned from view function

### ISSUE THREAD

**Issue by e1ectronic** [leeoniya/domvm#141]
I've found some confusing inconsistency with the use of `this` in the object, returned from view function. 

```
function View(vm, model) {
  var obj = {
    render: function (vm, model) {
      ...
    }
  }
  return obj;
}
```

Such an object may consist of `render` function, others function (for example `init`) and some data, so it is rather natural to use `this` in order to reference this stuff inside object.

What I discovered is that `this` in `render` function is not the same as `this` inside other functions (`init`, etc.), and I think it is very counter-intuitive.

Consider the following example: https://jsfiddle.net/532ote66/2/

`Clicker1.init` makes `onclick` binded to `this` in `init`, but inside `render` function `this` is changed to `vm`.

Maybe it would be better to discourage returning objects from view function, or check if these objects have only `render` and `diff` entries? If the initial idea was to patch `vm` using object as template, then I think, one can do it just fine without returning objects from view functions.

**Comment by lawrence-dol** [comment]
> What I discovered is that `this` in render function is not the same as `this` inside other functions (init, etc.), and I think it is very counter-intuitive.

Javascript's dynamic `this` is wholly confusing if you are used to static/syntactic `this`. This is because the context changes with invocation source, not with the invocation target. Which is why I avoid it like the plague.

Unfortunately, if DOMVM is going to try to do something useful with `this`, it should ensure that the `this` value is consistent when the hooks are invoked. Personally, I would prefer to just drop the use of `this`.

**Comment by leeoniya** [comment]
there's a reason that `this` is only ever mentioned in the context of ES6 class views (which are OO sugar for js).

inside many functions that are invoked by domvm itself `this === vm`. this includes the main view closure, render(), diff(), didInit(). event handlers and some hooks don't - maybe they should to be uniform. custom things that domvm does not invoke are your responsibility. in fact, if domvm was to auto-bind `this` in all the functions of your returned object, it would almost certainly bind them to `vm` and not to the returned object itself, which is not what you're asking for here either.

`this` is generally a discouraged pattern in JS and is precisely why `vm` is passed directly into all functions [even those where `this === vm`] rather than requiring users to use `this` and guess at what it actually is within each call context.

your example is rather strange in that it jumps through hoops to avoid using the view closure for its precise purpose - to isolate and scope all UI-related code. if you really want to go full-`this`, you can use domvm's ES6 class views and simply transpile them down to ES5 using Babel.

**Comment by leeoniya** [comment]
another issue (at least with your fiddle) is that if domvm bound `this` to your returned global object, then every new view instance of that type would re-bind to the same object. you would need to make a copy of this shared object including cloning its functions prior to returning it from the view closure, which you aren't doing here.

long story short, avoid using `this` in domvm views. as described in the readme, domvm works best as a lightly-coupled view layer that interacts with and renders your existing app state/models/api. feel free to use `this` in the domain/model layer of your app as necessary.
