### ISSUE TITLE
Lifecycle Hooks

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#15]
@barneycarroll i noticed your `mithril.exitable.js` repo for animation hooks and also remember you asking a while back how I would handle animating on removal. df2e45cb75caf30b07912624d01e84a3aa2c06ae is the result.

lifecycle hooks:
  - nodes: {_hooks:} - will/didInsert, will/didReuse, will/didMove, will/didRemove
  - views: vm.hook() - will/didRedraw, will/didMount, will/didUnmount

`will*` node-level hooks allow a Promise return and can delay the event until the promise is resolved, allowing you to do what you need to CSS animate, etc.

`will*` view-level hooks are not yet promise handling, so cannot be used for delayed anims yet, but you can just rely on the view's root node's hooks to accomplish the same thing, just not externally like you can hook vms.

there is no redraw-locking during pending promise resolution right now, nor are multiple promises coalesed by `.all()` or similar. so there's a possibility of getting the vtree into a confused state if there are complex staggered/unaligned animations of sibling nodes. this has not been tested. how do you handle this in `mithril.exitable.js` besides global redraw lock (& queue?) ?

here's a demo [1] of all the hooks firing (color coded by type). `didUnmount()` is excluded since it still has some issues WRT the fact that it does recursive bottom-up child removal.

[1] https://leeoniya.github.io/domvm/demos/lifecycle-hooks.html

**Comment by leeoniya** [comment]
the demo is a bit rough as it requires directly interacting with DOM eg `node.el.classList.remove("removing");`. this may be okay, but ideally you should be able to use a non hook-invoking version of `vm.patch(node, {style: ...})`. I'm thinking of a good way to get this done since `patch` takes oldNode/newNode, so would require a somewhat clumsy `vm.patch(node, [node.tag, {style: ...}, node.body])` that would also patch the children and invoke hooks, etc.

i like the terseness of the declarative style of snabbdom [1] for animations that could eliminate a lot of the rAF boilerplate in the demo if I implemented them as sugar over the hooks. they're more limited in what they can do vs raw hooks but likely cover 85% of what you'd need them for.

i was considering adding syntax like this to the `style` object: `_wr-opacity: [initialVal, rafDelayedVal]` (willRemove opacity values). or `_wr-class: [initialClass, rafDelayedClass]` to the props object, but it's a lot of syntax pre-processing overhead.

kinda interested in seeing how nicely i can reproduce the reorder-anim demo [2]

gonna sleep on it..

[1] https://github.com/paldepind/snabbdom#delayed-properties
[2] http://paldepind.github.io/snabbdom/examples/reorder-animation/

**Comment by barneycarroll** [comment]
Hiya @leeoniya, in answer to your question, Exitable simply freezes global draw. This means that any changes to the view model over the course of an exit animation (including other exitable components disappearing and triggering their own exits) is batched and takes course during the first redraw after the last animation.

Your question prompted me to reflect on whether this really was the best strategy. It's not difficult to imagine somebody wanting their application lifecycle to carry on undisturbed while exit animations occur. Surely something must be possible with `{ subtree : 'retain' }`? Well at this point we quickly realise that Mithril is not the ideal library for that level of control. The problem returns to the fact that view focused libraries that are agnostic as to model structure can detect a change in the view model but they can't infer the semantics of its cause. From a user perspective, a modal slowly fading away while they carry on working on editing their todo list sounds like an obvious, trivial thing. But we're not in a position to be able to determine that that's obvious: as far as we know, the thing animating out could be one of the todos. But then, how do you resolve new list states. including order changes, with the fact that an old item must remain while it exits? Besides, Mithril is intrinsically global in its treatment of the view: when you go against that, you raise all sorts of conflicts with no procedural answers. So basically, saying "no" to redraws while animating out saves you from a can of worms :)


Snabbdom is great. I hadn't seen the `delayed` property, but that's *ingenious*. Expressing one state and the next in a single stateless snapshot sounds like heresy, but it's so useful. Previously I had been keeping `drawn` flags in my components, writing imperative code in my views to toggle them, and writing ternary style properties. That's really neat though. Having said that, it's actually confusing to read a virtual DOM expression and understand that the immediate style properties could only be a starting point — if anything, you'd expect the persistent styles to be the ones immediately under `style` and the disposals initial, disposable ones to occupy a non-standard hook. After all, the point of this special API hook is to define starting points for animations — if something fades in you don't want it to be visible on first draw — but that starting point is the exception to the rule; if I find I need to tweak appearance, I shouldn't be thinking "right, I should probably look under `style.delayed`".

TBH Snabbdom doesn't really need that convoluted hook. Distinct starting styles are an implementation detail that can and should be safely tucked away somewhere more appropriate — the obvious place for this is `willInsert`: since any virtual node is entirely disposable, modifying if once on that initial hook is exactly what's needed.

Your distinction of 'move' as a lifecycle hook is interesting. One thing I think everybody can agree on is that detecting an insertion in Mithril is a terrible API. The fact that 90% of `config` use cases demand the entire application logic to be nested in an if condition is just stupid. So in a way, it's admirable that I wouldn't have to write my own logic to determine that something has moved in DOMVM. It does raise some questions, for instance "where was it before?", which one would imagine to be pertinent. The problem right now (as far as I can see) is that in order to preform a movement animation, one would need to record a reference to the old live DOM in 'willMove' and then determine the right animation conditions with reference to those in 'didMove'. Is that a problem? Should conditional modifications occur in the otherwise generic lifecycle method signature? Not sure. I am currently working on a bunch of example animated virtual DOMs for Exitable, which might help us with questions like that. Arguing about API ergonomics without use case references is difficult ;)

As far as calling your demo dirty, I don't think direct live DOM modification in application code is a sign of failure in the virtual DOM API. It's only a problem if live changes linger on in a way the library isn't aware of that cause problems later on. The notion that different states of CSS can express all desirable animations is naive — as a designer, CSS transitions are often not enough, and when they aren't it's *horrible* to try and shoehorn intended behaviour into them. Unless the virtual DOM library is saying it can account for every implementation detail of the whole animation — which to be frank is a terrible idea — then I think it's essential and intuitively obvious to expose the live DOM so that an external library can do the work.

**Comment by leeoniya** [comment]
thanks for your feedback!

> It does raise some questions, for instance "where was it before?"

yes, this is on the todo in fact and should be trivial to feed to the did/willMove hooks as args. right now all node hooks get the node itself as the first arg. i didnt wamt to commit to wildly dissimilar hook sigs beyond that just yet. i also had the initial thought to feed it oldIndex as arg #2 into the will/didmove. will/didReuse already gets oldNode, newNode so you can do your own diff to determine if it's an actual "update" or not. i have a commint in the demo that says DIY diff :) a d does just this (diffs content) since domvm doesnt do eager diffing before patch but does them deeper and lazily.

re snabbdom, the delayed css declarative style looks very tempting to me and very easy to add as sugar but already i see how limited it is. in my very basic demo i turn the div red pre-remove then in the nexttick must kill that same class to fade out. only the second action corresponds to the "delayed" and the first on is not the initial class, so you hav to use a hook anyhow. instead of just delayed you need an immediateDelayed and a delayedDelayed or something else splot it into prev/post hooks or other hacky things which always rear their head in overly-declarative libs/DSLs.

**Comment by leeoniya** [comment]
Hooks slated for renaming for clarity WRT actual DOM ops performed and vdom terminology:

```
Reuse -> Recycle
	willRecycle(node, newNode)
	didRecycle(node, oldNode)
Move -> Reinsert
	willReinsert(node, newIdx, newParent)
	didReinsert(node, oldIdx, oldParent)
```

Right now, reinsert can only happen within same parent so new/oldParent will always match, but could differ in future for transplanting components, etc. Dunno yet.

I think I'll init a "hook ctx" that persists between matched will/did hooks. This'll let you remember any prior state from `will*` hooks for use in `did*` hooks without having to create an external retention mechanism and allows you to keep/reuse a hooks object without recreating the hooks for every single node.

Question is, how to pass this `ctx` through to hooks?

  - As arg? which? 1? 2? Hurts ergonomics, where would you stick in above examples?
  - As the `this` not to pollute args? Too magical?

```
willRecycle(ctx, node, newNode)
willRecycle(node, ctx, newNode)
```

`ctx` is optional, and i dont wanna burden arg 1 with an optional thing for the sake of restArgs uniformity/beauty. Leaning towards `this`, despite disliking it.

**Comment by barneycarroll** [comment]
Isn't this `ctx` redundant too? I would keep all my view data on the higher scope view model.

**Comment by leeoniya** [comment]
For view-level hooks it is. For node-level hooks it isnt if they're static and shared. Consider:

```js
function MyView(vm, data) {
	// shared node hooks
	var nodeHooks = {
		didInsert: node => {...},
		willRemove: node => {...},
	};
	
	return () =>
		["ul", data.map(item =>
			["li", {_hooks: nodeHooks}, item]
		)];
}
```

In each hook invocation you may want a fresh context for the current node. You *could* technically piggyback on the node itself by assigning your own custom prop to it like `node.__myCtx = {};` and this will of course still be accessible in both `will` and `did`. But there's still extra management with cleanup, etc. and poor interaction/collisions with other hooks. On the other hand, this would be a good hack if you did in fact need cross-hook communication outside of matched will/did pairs.

**Comment by barneycarroll** [comment]
I don't understand. Why is the `vm` not suitable?

The point is the user has several opportunities to get hold of unique identifying objects. These can be used directly as storage — `vm.state = 'foo'`, or used as keys in maps if the user is afraid of pollution or collision — `states.set( vm, 'foo' )`.

**Comment by leeoniya** [comment]
> I don't understand. Why is the `vm` not suitable?

Yes, one can always do the bookkeeping manually in the closure. I would not set anything on the vm that you dont explicitly want to expose to the outside world. There's actually a pre-initialized empty export object `vm.exp.*` to expose internal view APIs or state (for suggested uniformity and collision avoidance).

```js
function MyView(vm, data) {
	// some per-node stuff to remember between hooks
	var wmNodes = new WeakMap();

	// shared node hooks
	var nodeHooks = {
		willInsert: node => { wmNodes.set(node, {someProp: "mooo"}); },
		willRemove: node => { wmNodes.get(node).someProp; },
	};

	return () =>
		["ul", data.map(item =>
			["li", {_hooks: nodeHooks}, item]
		)];
}
```

I'm not sure how much a `ctx` would improve ergonomics if it's only limited to matched will/did hooks. It seems more useful to have cross-hook retention as above. So ctx would be most useful if it was already a flat vm-level weakmap of all nodes. seems expensive and unnecessary tho.

**Comment by leeoniya** [comment]
86dc536512c180d2ead3955ec6932988397ecb55 renames the Reuse and Move hooks.

**Comment by barneycarroll** [comment]
What prompted 'reinsert' instead of 'move'?

**Comment by leeoniya** [comment]
`reInsert` communicates the fact that it gets detached from the dom more clearly, IMO. and also matches the internal implementation of using `insertBefore` for both initial insert/hydrate during mounting and re-insert/reorder on redraw. for node-level stuff I want to match the underlying DOM terminology as closely as possible. obviously, "recycle" is vdom specific.
