### ISSUE TITLE
vm question

### ISSUE THREAD

**Issue by iamjohnlong** [leeoniya/domvm#151]
It's it a bad idea to set extra params on the vm? 

I want to use the object views like so:

```js
const View = {
  init(vm) {
    vm.state = {
      foo: 'bar'
    }
  },
  render(vm) {
    return el('div', vm.state.foo)
  }
}

```

**Comment by leeoniya** [comment]
if you're talking specifically about `vm.state`, i'm actually planning to keep it unused for exactly this purpose. perhaps even reserving `vm.setState`, so you can imitate React as you see fit. i was also thinking to leave `vm.api` reserved so that external view methods can be put there.

setting other vm properties at-will risks collisions with current or future vm internals.

**Comment by iamjohnlong** [comment]
yes I'm specifically talking about `vm.state` for the internal state of a view component. good to know thanks! I haven't ran into any bugs in v3, everything is working as expected.
