### ISSUE TITLE
css transitions / hooks

### ISSUE THREAD

**Issue by iamjohnlong** [leeoniya/domvm#159]
i'm not sure if this is a bug or just  the way it's written, but an error is thrown when nodes are being removed if you add messages fast. i haven't done much with transitions and domvm so it very well could be an error on my part. im building off what you have in the hooks demo

```console
Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

add a couple real quick and you should see the error.

https://jsfiddle.net/mbsj3q17/1/

**Comment by leeoniya** [comment]
i'll look into this later today.

**Comment by leeoniya** [comment]
amusingly, this bug only manifests itself in Chrome. Edge and IE work fine.

here's a much smaller repro: https://jsfiddle.net/gpf8qz25/

**Comment by leeoniya** [comment]
so i never did figure out why it only errored in Chrome (it should have errored in others also)

the diagnosis is that during sequential redraws it was queueing up extra removals for nodes that were already queued and just waiting for promise resolution. i've added an internal `_dead` flag that's set if a promise is returned from willRemove so that the reconciler doesnt try to pluck them again on other pre-resolution redraws.

working: https://jsfiddle.net/cup40vu7/

thanks for the report!

**Comment by leeoniya** [comment]
this is the second willRemove bug i've had to squash this week (#153 being the other). the async/transition persistence aspects are definitely getting some much-needed exercise recently. i'm not surprised at all, it's probably the trickiest part to get 100% correct.
