### ISSUE TITLE
Unkeyed input caution.

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#167]
I find the following dev-mode warning puzzling: `UNKEYED_INPUT: Unkeyed <input> detected. Consider adding a name, id, _key, or _ref attr to avoid accidental DOM recycling between different <input> types.`

Could you offer a bit of background as to why this is (may be) an issue, please?

Particularly, I am finding it's hard artificially come up with a key for all inputs, it's unnatural to need to do so, and it's extremely easy to forget to do so if you don't need a key for other reasons (which, to date, I've never had). It seems like, on the surface, DOMVM should not try to recycle input elements if they are internally problematic.

**Comment by leeoniya** [comment]
> DOMVM should not try to recycle input elements if they are internally problematic.

the problems occur if you have 2+ sibling inputs where at least one is conditionally rendered. when one of those inputs disappears it's possible the remaining one will be reused in its place. there are a bunch of situations where this will cause problems and the warnimg can actually be expanded to any focusable elements, too (buttons, textareas, even links!).

a simple example would be some multi-step guide with adjacent OK and CANCEL buttons. if you have CANCEL focused and some condition causes CANCEL to be removed, that button can be patched to be the OK button and still remain focused!

the same goes for any temporary text you may have entered into a textbox without syncing it back to your app. you may end up with a Date input that has a Name value in it.

there are only a few ways to have domvm not recycle something: give it a key, have a different tag, have a different view.

it's impossible for domvm to know if there will ever be another recycleable sibling rendered next to an input or if the input was/is rendered conditionally, or if you're doing enough back-syncing of temp input state to avoid these hazards. if you have a static form layout, you'll not run into these issues; they only occur in conditional rendering scenarios, but there's no way for domvm do assert this.

you can silence that warning or replace it with your own function that does deeper testing of your vtrees and only shows it or ignores it under specific conditions (eg the parent node is a `td` with body.length == 1)

also see https://github.com/leeoniya/domvm/issues/134

**Comment by leeoniya** [comment]
correction, the value-transfer thing can't happen since those values diff to the actual dom, but the focus-loss (and any selection/cursor position reset, undo/redo history, etc) can:

https://jsfiddle.net/3Ldet274/

try clicking the first button a few times and see that it stays focused despite inverting its meaning, making it really easy for a user to confirm something just by double-tapping accidentally.

the cross-`[type]` recycling of `input` can also be problematic as seen in #134. while it's not complex to fix, that check needs to live in a hot path and test every single vnode additionally for `if (node.tag == "input")` which gets quite expensive.

keying/naming is a simple way to avoid these issues without extra caveats.

**Comment by lawrence-dol** [comment]
From #164:

> I literally just finished adding name to all my inputs. I'm satisfied!

Hmmm. I'm not. The construction of input elements in my code is always buried under a layer of abstraction for the app; my code just calls `crtTextField`, `crtPasswordField` etc, and passing a name down solely for the purpose of disambiguation is unnecessary clutter and an accident waiting to happen.

I think `input` and other elements that have this problem should not be eligible for recycling.

I assume that simply assigning they a serial number for an id is going to have other undesirable performance implications, since every redraw will then have a different input, right?

Out of curiosity, what's the performance hit of not recycling?

**Comment by leeoniya** [comment]
> Out of curiosity, what's the performance hit of not recycling?

if you have a grid, where each cell contains an input, then it's massive.

a better question is, would you find it less surprising if all your inputs, textareas and buttons lost their focus, redo/undo history, selection and cursor position on each redraw?

to me, the answer is rather obvious.

again, this caveat applies only to sibling elements. it's not an unusual requirement in vdom libs that you must key uniform lists (or similar siblings) to avoid surprising recycling behavior. unfortunately, there's not a good solution here and the tradeoffs made by the current behavior were well-considered and, frankly, not difficult to understand.

**Comment by leeoniya** [comment]
one option would be to only show the warning for inputs/textareas/selects whose vnodes do not explicitly set the `value` or `checked`. this would make the warnings less chatty. maybe.

**Comment by lawrence-dol** [comment]
Ohhhh. By recycling, you mean not replacing an element that is still in the view with a reconstructed version of itself! Well, of course that changes everything.

The word "recycling" connotes taking an existing object and repurposing it for some other use. As in "we recycle used paper into egg cartons" or "we recycle egg cartons for a new batch of eggs". Not, "we recycle egg cartons because every time we remove an egg to cook we retain the existing egg carton and put it back in the fridge. Just for the record the word you want is not "recycle", but "retain" (retention) or a synonym like "preserve" (preservation) or perhaps "persist". Terminology matters.

Therefore, the need for a unique key is for reliable *preservation* of DOM elements corresponding to vDOM elements that persist across redraws.

So, the answer to "a better question", is yes that would be an awful idea, and I need to ponder this further now I understand the actual problem being addressed.

> if the warnings bother you, then just disable them.

I'm not bothered by the warnings, I am trying to understand what it's warning me about so I can address the concern properly.

**Comment by lawrence-dol** [comment]
> only show the warning for inputs/textareas/selects whose vnodes do not explicitly set the value or checked

Wouldn't that suffer from the same problem if the value happened to be the same and one was omitted?

**Comment by lawrence-dol** [comment]
So the name (et al) of each input needs both to be unique and to persistent for the life of the view.

**Comment by leeoniya** [comment]
in vdom terminology "dom recycling" means reusing the already-created dom. (there is also technically vtree recycling enabled by `lazyList`, but that's not this situation).

which dom elements represent which vnodes before and after a redraw() call is governed by being able to match up the new vtree to the old vtree, recycle the dom as best we can and patch it to match. whether that recycling is deterministic depends on how much uniqueness we can extract about each sibling.

> Wouldn't that suffer from the same problem if the value happened to be the same and one was omitted?

if only one is omitted i *think* it will cause a problem only half the time, feel free to read through the actual attr-diffing loop [1]. it doesnt really matter because i will be showing warnings for all omissions.

> So the name (et al) of each input needs both to be unique and to persistent for the life of the view.

keying ensures deterministic dom recycling. keys only need to be unique within their parent. elements can be keyed by [2]:

- `_ref` (must be unique per view anyways)
- `_key` (must be unique within parent)
- `id` (should be unique for whole document)
- `name` (hopefully unique at least within parent)
- `input[type=radio]` inputs will be keyed by `name`+`value`

[1] https://github.com/leeoniya/domvm/blob/3.x-dev/src/view/patchAttrs.js#L54-L80
[2] https://github.com/leeoniya/domvm/blob/3.x-dev/src/view/initElementNode.js#L74-L81

**Comment by lawrence-dol** [comment]
Now I understand. I do need to add a name to every input, which I can do easily since each input is associated with a unique model field in some way.

Thanks for your patience with me.

[I still don't like "recycling" to refer to this mechanism, though now I understand why it works in the context. I think the broader intent of the process is not simply to "recycle" nodes, but to "preserve" nodes that still exist in the view and that the community would be better served to think of it in those terms.]

**Comment by leeoniya** [comment]
> I still don't like "recycling" to refer to this mechanism

js is filled with reinvented terminology for old shit rather than adopting what already existed. polyfills? they're called "shims" literally everywhere else.

i added the rest of the input family to the warning list in https://github.com/leeoniya/domvm/commit/69ed88538db9dae47524d1a578f85602f5b80cc1
