### ISSUE TITLE
VM/Node finders

### ISSUE THREAD

**Issue by yosbelms** [leeoniya/domvm#17]
## Motivation
Find a sibling, children, or a node with a complex related position. Find a `node` or a `vm` inside the tree.
## Proposal
Two methods for `vm` and `node`. Those methods are `down` and `up`.

**down:** finds a item which fulfill the specified condition in the tree starting from the children of the node in question. Example:
```js
var node = vm.down('someKey')

```
Finds a `node` or `vm` with that key starting from the `vm` children

**up:** the same with `down` but iterating over parents up in the tree.
```js
var parent = vm.up('someKey')
```
Find a ancestor whith `someKey` key.

Usage example:
```js
// root view with 2 keyed children
function RootView(vm, data){
    return function(){
        return ['div'
        	[ChildView1, data, 'ch1']
        	[ChildView2, data, 'ch2']
        ]
    }
}

// children view 1
function ChildView1(vm) {
	
	function click() {
		// redraw a keyed sibling
		// without redrawing the parent
		vm.up().down('ch2').redraw()
	}

	return function() {
		// execute update on click
		return ['button', {onclick: update}]
	}
}

// children view 2
function ChildView2() {
	...
}
```
`ChildrenView1` redraws the sibling without triggering redraw in the parent.

**Comment by leeoniya** [comment]
the core exposes the vtree for you, so this is something that you can do already. not sure if the core needs it.

vm.node - vnode
vm.node.parent - parent vnode
vm.node.body - children (if array) or content (if value)

**Comment by yosbelms** [comment]
Agree, it is really very straightforward and the tree organization is well done. But, what about if you want to trigger redraw from a deep child in a complex tree?

With mi proposal:
```
vm.down('deep-child').redraw()
```

**Comment by leeoniya** [comment]
Optimizations such as wanting to trigger redraw of a deep child from a parent are usually premature.

The parent should not be unaware of its descendant vms except to know that something has mutated (purpose of emit) - this is what allows free composition/swapping. When you start targeting specific parents or specific children, you have now created a binding that must be thought about and maintained. I am not convinced this is something I want to encourage.

I'm even iffy about encouraging the use of targeted emit and would prefer to have it always trigger root redraw because the children should not know which parent they're under or where they live in the hierarchy as this adds compositional restrictions.

**Comment by leeoniya** [comment]
additionally, `vm.down('deep-checkbox').el.checked` should never be needed.

the vtree is not just an alternative to the dom. nor is domvm jQuery - you should never have to read the DOM except to get computed style values like element offset, scroll position, etc.

the checked value comes from either an initial model condition or an event triggered by the user. if it is an event then it should be synced to the model via handlers (and optionally emit) and then you can read it back from the model directly.

**Comment by yosbelms** [comment]
>  you have now created a binding that must be thought about and maintained. I am not convinced this is something I want to encourage.

This behaviour is borrowed from ExtJS, React makes possible something similar. The truth is that it removes boilerplate. I don't want to (no one wants) write/read `vm.node.body[1].body[2].el.focus()` if I can do `vm.node.down('editor').el.focus();`

BTW, The TodoMVC example is almost ready I will point you when it be done.

**Comment by leeoniya** [comment]
> The truth is that it removes boilerplate

Only *if* the standard pattern is to operate directly on DOM nodes. domvm encourages API-first modeling. That is, you would instead do `myEditor.focus()` or `myEditor.viewArea.focus()` without any knowledge of the actual DOM.

In turn, `myEditor.focus()` would simply set a `myEditor.focused = true` and issue its own `vm.redraw()`. The focused condition is then handled by the vm's `didRedraw` hook or by a `focused` attribute set conditionally by the template/render.

React is a UI-centric lib so all it knows is DOM and data. domvm is not ui-centric, it's meant to be a view layer over plain js models with an their own api whose views can also be composed.

**Comment by leeoniya** [comment]
if you're wondering how `myEditor` itself is meant to access the actual textarea node, that's what `vm.refs` is for.

**Comment by yosbelms** [comment]
I will explore `vm.refs` deeper. All those PR's are not made whith the intention of merging, rather to discuss and open issues starting from it. The only I'm using for TodoMVC is #18, which a similar aproach to React solution, virtual-dom addresses the same issue using `aria` prefix, example `aria-checked`.

**Comment by lawrence-dol** [comment]
> React is a UI-centric lib so all it knows is DOM and data. domvm is not ui-centric, it's meant to be a view layer over plain js models with their own APIs whose views can be freely composed. anything you can do from the UI should be doable via api.

I have to side with @leeoniya on this one. The beautiful, and game changing effect of both Mithril and AFAICT domvm is that the view is simply, only and always a direct rendering of the current model state; if you want to change the view you change the model and redraw and the view is updated.

There is only one slight edge-case to this as a principle and that is some input elements where the event which allows the model to be changed means that by definition the view already reflects the data. For example, typing in an input field which have key handlers attached in order to detect specific keys like ESCAPE and ENTER (to cancel and save). Those event handlers should not cause a redraw by default or the redraw should be easily and cleanly suppressible at the level of the specific handler.

As a concrete example of this, consider a list filter field. I want to know about keys typed so I can (a) detect changes with a 500 ms de-bounce and update the list when the user stops typing, and (b) I also want to detect ENTER and ESCAPE at a higher level so I can immediately update or cancel filtering accordingly. Mithril's global-redraw suppression is a kludge and I had a long discussion with Leo as to why it's a kludge, though I was ultimately unable to convince him of this, even though his first "fix" broke immediately for the reasons I told him it would. I also knocked up a simple demo which demonstrated that it produced tangibly visible keying lag on a realistic list with 1,000 items on a mid to high end desktop PC.

**Comment by leeoniya** [comment]
@yosbelms 

I have added a todo demo i had laying around: https://leeoniya.github.io/domvm/demos/todo.html

It doesnt use event delegation cause the list is small and doesnt need it. It also doesnt use any of the conveniece helpers of the `watch` module for auto-redraw assistance. Rather than `"checked"` attribute it uses `".checked"` property as this is always consistent and allows nodes to be reused without actually juggling prop/attr and asking the DOM for the "real" value.

There's some work to be done with properties like `checked` and other form elements as mentioned in `citojs` docs where initial attr vals dont always match the actual value: https://github.com/joelrich/citojs#input-elements, however this demo demonstrates some of domvm's idiomatic style.

**Comment by leeoniya** [comment]
In this demo, the `TodoList` model is view-unaware. If you wanted TodoList's api methods to affect the view, you could make them view-aware in a number of ways (by wrapping the view in the model or passing the vm to the model) and invoke redraw either manually or by using `watch` props.

**Comment by leeoniya** [comment]
Here's the same todo that embeds the view into the model, so all API calls now redraw the view and all the handlers from the view simply invoke the API. You can take this initialized view and embed it any other template, composing "components" as needed with full API access. It's supremely elegant, IMO.

With some setTimeout calls for API/redraw demo: https://leeoniya.github.io/domvm/demos/todo-alt.html

**Comment by yosbelms** [comment]
@leeoniya I have seen your todomvc examples, it shows the capabilities of domvm context's sharing. However I pushed a implementation of a full working standard-todomvc examaple.

**Features**
* insert/remove
* edit(dbclick on the task, cancel by escape, commit with enter)
* toggle sigle task
* toggle all
* filters (all, pending, completed)
* footer hidden when there is no task
* localstorage
* deferred saving to be UI framerate friendly(not part of the standard)

running at: http://yosbelms.github.io/domvm/demos/TodoMVC/

**Comment by yosbelms** [comment]
@lawrence-dol, you got the idea, we must not ignore the underlaying techonolgy. When doing RAD we need flexibility especially when we are new to the framework, the best practices are reserved for refactoring, discipline, and expertise, IMMO. Even further, there is some fine tunnings which are possible only accessing to the underlaying technology. Is impossible to cover all possible "use cases"  for a non-bloated library, hence it may offer basic flexibility.

**Comment by leeoniya** [comment]
@yosbelms Briefly looked over it. Looks pretty good.

Some initial feedback:

> vm.emit('_redraw:1000');

This convention looks clunky to me and is the main reason I abstracted it as `vm.emit.redraw(targ, args)`. Where targ defaults to 1000. You can use this if you prefer, but I suspect most users (myself included) will not enjoy this convention for such a common thing.

> `vm.emit('_redraw')`

I'd avoid emitting untargeted _redraw as it will invoke redraw on every ancestor vm as it bubbles since they all implicitly have handlers for it. If you want to redraw the current vm, just use `vm.redraw()`,`vm.emit("_redraw:0")`,`vm.emit.redraw(0)`. For parent, `vm.emit.redraw(1)`, etc..

You could avoid calling redraw everywhere by using the `watch` module. You also can create multiple watchers that have different callbacks that refresh different vms or sets of vms.

```js
// create a watcher with handler
var w = domvm.watch(function(e) {
	e.vm.redraw();
	// or
	e.vm.emit.redraw();
	// or
	someClosuredVm.redraw();
});

var x = w.prop("initial value");

// read back value
x();

// or using via .toString invocation
""+x;

// setting new value invokes handler
x("new value");

// sets new value but prevents handler from firing
x("another value", false);
```

The downside you'll need to wrap all your values in `.prop` shallow mutation observers (similar to Mithril).

I'll dig into it a bit more later today.

**Comment by leeoniya** [comment]
btw, domvm templates support getters as nodes, node body and prop values, so you can just pass `x` and not have to do `x()`. Either way the wrapper has the appropriate `.toString` in other places.

**Comment by leeoniya** [comment]
> `vm.node.el.classList.add('editing');`

This is a an unnecessary optimization. I would stick with just redrawing the entire item and relying on the template to add this class for you so that it reads more obviously from the template. The individual item's vtree is laughably small to have to employ this non-idomatic behavior.

**Comment by leeoniya** [comment]
> e.preventDefault();

not needed if you return `false` from the event handler [1].

[1] https://github.com/leeoniya/domvm/blob/master/src/view.js#L847

**Comment by yosbelms** [comment]
> This convention looks clunky to me and is the main reason I abstracted it as vm.emit.redraw(targ, args)

`vm.emit.redraw()` is ad-hoc and looks a bit odd whith the rest of the API, due to is not possible to reproduce something similar in the app space. Example:
```js
vm.on({
	'myEvent': function() { }
})
vm.emit('myEvent')

// but we can not do
vm.emit.myEvent()
```
So, in a first glance, it is a bit confusing to me.

> If you want to redraw the current vm, just use...

Sometimes I just need to redraw a vm which is anywhere inside the tree. Here is when `up/down` plays nice. See the following picture which illustrates the structure of the app:

![sin titulo](https://cloud.githubusercontent.com/assets/12763081/13088361/91f5975a-d4b1-11e5-966b-f182f5da1a4d.png)

Currently if I want to redraw the `Footer` from the `Main` view I have to redraw the `App` which will redraw `Main` in consequence. I would use `vm.node.up('main').down('footer').vm.redraw()`, simple and performant, or `vm.up('main').down('footer').redraw()`

> You could avoid calling redraw everywhere by using the watch module.

Great, but I hope I could make a performant and maintainable app whithout it, however it is very usefull, I'll explore later.

> `vm.node.el.classList.add('editing');` This is an unnecessary optimization

I ike to call it **user experience**. However if this app targets to be part of the domvm examples it must use a idiomatic behaviour instead. I have to say the idiomatic way was in the first version, `el.classList` appeared later as part of the refactoring proccess.

**Comment by leeoniya** [comment]
@yosbelms 

> `vm.emit.redraw()` is ad-hoc and looks a bit odd with the rest of the API, due to is not possible to reproduce something similar in the app space.

I do agree, and I'm accepting other solutions :), but making the user emit magic string-based events is worse from my perspective. I'll take convenience for frequent cases over absolute uniformity 95% of the time, especially since the uniform method is extremely unpleaseant in this case.

Maybe `vm.redrawRoot()`, `vm.redrawParent()`, `vm.emitRedraw(targ)`, `vm.reqRedraw(targ)`. Perhaps it's better to take `emit` wording out of it so it doesnt need to imply the underlying system. I dunno, no clear winners at this time.

> Currently if I want to redraw the Footer from the Main view I have to redraw the App

Actually you don't. You can pre-init the sub-view vms imperatively and insert them as nodes into the App parent tpl. That's a huge selling point of domvm, in fact.

```js
function AppView(vm) {
	var views = {};
	views.main   = domvm.view(MainView,   todos, null, views);
	views.footer = domvm.view(FooterView, todos, null, views);

	return function() {
		return (
			["#app",
				views.main,
				views.footer,
			]
		);
	};
}
```

Now each sub-view can use its `vm.imp` to access the vms of the others directly, this includes if they move around, etc. This has the least overhead, most power but probably not the best ergonomics.

The up/down approach is much more pleasant to use but is less powerful, relies on a-priori knowledge of where the other view is in the tree relative to itself (some compositional lock-in) and has the overhead of searching/traversing. I'm definitely considering it. The concrete examples are much more helpful than just PRing the solutions :) Thanks.

> I like to call it user experience

I like to call it developer-unfriendliness for no good reason. Your users will never experience this difference because both versions will be repainted by the browser *well* within in a single frame. But any collaborators will have to figure out where, other than the template, you're adding/mutating classes/styles. There's literally no valid reason to do it in this instance.

**Comment by leeoniya** [comment]
ok, i thought of another method to redraw related but disjoint views which i like better than up/down and is more uniform with the emit system: unjailed keys.

the idea is that you can specify a key like "!appFooter" declaratively on a node or vm and this key would populate into every ancestor vm's keymap, so u gotta be careful about collisions (see exclamation?).

now you can use the emit system to issue some custom ["redrawSubview", "!appFooter"]. your redrawSubview handler would live somewhere in a common ancestor of the disjoint nodes/views but would have access to all unjailed keys without digging/searching overhead.

it's a compromise between imperative vm-passing/0-overhead and up/down composition lock-in and traversing overhead. you just incur a bit extra to bubble the keys up during every vtree rebuild.

i'm a fan. votes?

**Comment by yosbelms** [comment]
> both versions will be repainted by the browser well within a single frame

But not in the same CPU cycle. Does it?

I've thought of a `global event bus`, it decouples everything, se the snipet:
```js
function Footer(vm) {
	// listen here
	domvm.on({
		'toggle-todo': functionm() {
			vm.redraw()
		}
	})

}

function Header(vm) {	
	function toggle() {
		// notify
		domvm.emit('toggle-todo')
	}

	return function() { return (
		[....]
	)}
}
```
The above example is generic and lean, and it requires better support of event-driven in domvm. However there is more alternatives to look at.

More focused:
```js
// listen
vm.redrawOn('toggle-todo')
// notify
vm.emit('toggle-todo')
```


More clean:
```js
// listen
vm.on('toggle-todo', 'redraw')
// notify
vm.emit('toggle-todo')
```

**Comment by lawrence-dol** [comment]
Just in case I am not misreading the above comment (*)...

I would argue against adding an event bus and event hooks to domvm. Pure event-driven coding is a very specific paradigm, and while it should be trivial to wire interactions with domvm into an event bus, domvm should not provide and especially not require one. As a library its use should be obvious and imperative. Anything more is a layer on top.

(*) I may be entirely wrong.

**Comment by leeoniya** [comment]
@yosbelms 

> But not in the same CPU cycle. Does it?

Anything which touches the DOM/reflow requires no fewer than *hundreds* of CPU cycles - many more than any JIT-optimized diff in JS. Nits aside, I'm not gonna beat this dead horse. If you feel that you need this level of micro-optimization (which it is) at the expense of uniformity in your codebase for something so trivial, then great. Just keep in mind that if you intend to contribute docs, demos, tests or core code to domvm [that I'd want to merge], I prefer code clarity over sub-frame cycles when the expected quantity and frequency redraws/events is as tiny as the diff overhead. The only possible argument for this is battery life on a mobile device, but in this case you wouldn't touch any vdom lib with a 10-foot pole, or even a platform backed by DOM/HTML. For redraw-all-the-things, mousemove, touchmove, scroll, resize, etc. it's a different discussion.

If you really need to minimize the diff down to the node-level rather than vm, you could use `vm.patch(oldNode, newNode)` before resorting to raw DOM ops. But again, this requires additional effort. This 10k-cell table bench actually requires this strategy to stay performant but has to expose the sub-template generator plus a crafted node locator: http://leeoniya.github.io/domvm/test/bench/patch/

> The above example is generic and lean, and it requires better support of event-driven in domvm. 
> I would like you to get the idea, it is about comunicating by message passing, it should be multicast, scopeless, and declarative.

> I've thought of a global event bus, it decouples everything, see the snipet:

I think you just implemented 90% of your global bus in that comment :) ...which pretty much echos @lawrence-dol's sentiment. Despite being trivial however, it does decouple things rather nicely in some cases. Still, something about a global registry does not sit well with me. I vaguely remember reading rants about "COMEFROM"-style [1] and how event-driven systems quickly turn into spagetti that's hard to reason about. See the pros and cons in "When to Use It" section [2]. For intra-app communication, global event buses are likely best avoided. The situation for inter-app communication when each is written by a different party is less clear cut. There's a huge advantage to having some idiomatic global way to loosly link separate apps when imperative APIs are not accessible. For within-app (inter) I still prefer an unjailed keys approach where at least you have some inference over the effect-scope based on code structure. The emit system is already effectively a contained bus since you can register all your handlers at the root vm.

> PS: The TodoMVC is updated taking more idiomatic style. Check this out please.

Looks good. Though on Firefox and Edge the checkboxes look like shit.

[1] https://en.wikipedia.org/wiki/COMEFROM
[2] http://martinfowler.com/eaaDev/EventCollaboration.html

**Comment by leeoniya** [comment]
@yosbelms

On second look, all `vm.emit('_redraw');` should be replaced with `vm.emit.redraw()`. The first one is untargeted redraw and will trigger redraw one every vm individually during bubbling, including root at the end. There's no reason to do this. `vm.emit('_redraw:1000');` and `vm.emit.redraw()` will diff/patch the root *including all children* anyways.

This is exactly why I don't want people to use (or maybe even know about) the "uniform" version of emit for `_redraw`. I don't want to explain why this is a bad idea and how it will degrade performance for multi-level-view apps. Just use `vm.emit.redraw()` that has an implicit 1000 target or an optionally explicit target.

**Comment by lawrence-dol** [comment]
Not to be pedantic, but even as a private thing, `1000` is a rather arbitrary and obtuse magic number; I've learned over the years that as soon as you set such a number someone will come along with a legitimate use-case for `n+1`. Why not use plain `_redraw` (since `_redraw:0` is intuitively obvious for the current view) or `_redraw:*` to indicate a top-down global redraw?

**Comment by leeoniya** [comment]
@lawrence-dol 

`_redraw:*` reads to me as "any" or "every", or "each" and i did not want to reserve "root" because there is a plan to allow named keys to be used as targets, so i stayed with numeric to reduce complicating internal logic.

`1000` is not a reserved special-case number, it is simply a value large enough to climb up to any conceivable root - 1001 will work, 1e6 would work, 100 will work so long as your nested vm depth (*not* node depth) is <= than the target number - in real-world apps, 10 should be sufficient for very complex things.

The fact that redraw targeting rides on the emit system is a DRY implementation detail. it is not meant to be used in raw form by mere mortals. This is why I'm considering removing "emit" wording completely or provide a more obvious explicit wrapper method.

Really, I think the solution is just to remove the docs for the internals. No one asks questions, everything stays fast and if no one ever opens an issue, then it's a non-issue.

**Comment by lawrence-dol** [comment]
> _redraw:* reads to me as "any" or "every", or "each" and i did not want to reserve "root" because there is a plan to allow named keys to be used as targets, so i stayed with numeric to reduce complicating internal logic.

Well, redrawing from the root is redrawing "every" vm. One possibility is "_redraw:*ROOT"; I use leading `*` plus uppercase to connote special values all the time and they typically work very well and read much better than leading underscores (though that might be because I am so accustomed to seeing them as such).

> 1000 is not a reserved special-case number

True, but it's still "magic" in a real sense. Granted at 2 orders of magnitude greater than the largest depth expected it's probably very safe, but obviously special values are far preferable over numbers with special meanings. In other words, when I am working on DOMVM I will have to parse "_redraw:1000" whereas "_redraw:*ROOT" is (a) obvious and (b) can likely be optimized not to walk up the tree.

Not wanting to beat a dead horse; just my 2 dollars.

**Comment by leeoniya** [comment]
@lawrence-dol

I understand where you're coming from. However, `_redraw:1000` is only ever assembled once inside the 2-liner abstraction that is `vm.emit.redraw()`. I prefer to simply add a comment explaining what it is (if even necessary)  that gets removed during minimization rather than adding bloat and special parsing logic for "*ROOT", etc.

I did a quick implementation of unjailed keys (for vm's only, not nodes). The usage ends up being:

```js
var data = {
	a: "foo",
	b: "bar",
	c: "baz",
};

function updateData() {
	data.a = "moo";
	data.b = "cow";
	data.c = "now";
}

function AppView(vm, data) {
	vm.on("redrawMainAndFooter", function() {
		vm.keyMap["!main"].redraw();
		vm.keyMap["!footer"].redraw();
	});
	
	return () =>
		["div",
			data.a,
			[MainView, data, "!main"],
			[FooterView, data, "!footer"],
		];
}

function MainView(vm, data) {
	return () => ["strong", data.b];
}

function FooterView(vm, data) {
	var onclick = function(e) {
		updateData();
		vm.emit("redrawMainAndFooter");
	};
	
	return () => ["em", {onclick: onclick}, data.c];
}

domvm.view(AppView, data).mount(document.body);
```

Can't say that I love it more than creating imperative vms. There are a couple internal oddities as well.

1. `vm.keyMap` normally doesnt hold `vms`, but rather child indices, so the hash becomes non-uniform. I could keep it uniform but then you get ultra-ugly digging to get to the vm by traversing `childIdx -> node -> vm`.
2. Using `!` or any special char as the prefix ensures you cannot use dot notation for keyMap access to the vms. Dare I use a `$` prefix?

**Comment by lawrence-dol** [comment]
@leeoniya 

Fair enough. I have a big, isolated, prototype POF project scheduled, for which I am planning to get feet-wet with DOMVM. I don't believe I have any use for redrawing this way; I'd much rather inject the dependencies needed for each component. But we'll see; sometimes magic wiring using freestyle named things is really useful for loose coupling.

**Comment by leeoniya** [comment]
> I have a big, isolated, prototype POF project scheduled, for which I am planning to get feet-wet with DOMVM

Great, I hope the lib doesn't disappoint too much.

I am inclined to implement unjailed keys for several reasons. Pure imperative tree construction with dep injection is tedious; it's ok for maybe a few layers but quickly becomes a nuisance for deep structures. In addition, it's necessarily an inverted/bottom-up assembly ceremony from which structure inference becomes increasingly difficult to grok. The convenience of a flat sub-view map is undeniable and selective redraw should be made as friendly as possible in domvm for both imperative and declarative paradigms. A lot of work went into the nuts and bolts to make it a reality and it'd be sad not to offer some trivial wiring assistance.

I was wrong about the keyMap uniformity point, vms dont currently have keyMaps, only vnodes do.

I will add a `vm.keys` object for the purpose of holding unjailed refs and the `!` key prefix will be stripped for dot notation access.

**Comment by leeoniya** [comment]
unjailed keys done in https://github.com/leeoniya/domvm/commit
/d69f64659a34562b570400293c8bd1a81e914365

I also modified the emit system to halt on first matched event, so it now bubbles only until first match. This was done because I could not think of any reason to trigger (or have handlers for) the same event at multiple vm levels. The emit system was always meant to just bubble up to some specific/predefined handler in an ancestor, anyways. This change has the fail-safe side-effect that untargeted emits of _redraw will now effectively work the same as `_redraw:0` and `vm.redraw()`. Unless someone can convince me that DOM-like behavior would be truly useful in life-changing ways, it will stay this way.

unjailed keys:

```js
var data = {
	a: "foo",
	b: "bar",
	c: "baz",
};

function updateData() {
	data.a = "moo";
	data.b = "cow";
	data.c = "now";
}

function AppView(vm, data) {
	vm.on("redrawMainAndFooter", function() {
		vm.keys.main.redraw();
		vm.keys.footer.redraw();
	});
	
	return () =>
		["div",
			data.a,
			[MainView, data, "!main"],
			[FooterView, data, "!footer"],
		];
}

function MainView(vm, data) {
	return () => ["strong", data.b];
}

function FooterView(vm, data) {
	var onclick = function(e) {
		updateData();
		vm.emit("redrawMainAndFooter");
	};
	
	return () => ["em", {onclick: onclick}, data.c];
}

domvm.view(AppView, data).mount(document.body);
```

Alternatively, you can specify the keys in the props of the vm's root node (this has been the case for a long time, so just a reminder):

```js
function MainView(vm, data) {
	return () => ["strong", {_key: "!main"}, data.b];
}
```

**Comment by leeoniya** [comment]
I'd also consider switching from `!` to `^` for the prefix as it's visually a better indicator of what's going on (the reference to the vm is populated "up" to every ancestor). Will decide in the morning.

**Comment by lawrence-dol** [comment]
I can imagine multiple views actioning an event; consider that the event is descriptive of what happened rather than what needs to happen. Say, `vm.emit("CustomerAddressUpdated")` -- multiple vm's will be interested in that fact, say the list view and the detail view if the customer changed is currently selected.

If by event handlers, you mean normal things like handling keystrokes, then there is an excellent common use case for having multiple handlers see them and take action on them. Using my filter field as an example, the individual input field itself handles all keys looking for the user to stop typing, but the container handles ESCAPE and ENTER from all inputs looking for the user to cancel or commit their filter.

**Comment by leeoniya** [comment]
@lawrence-dol 

> If by event handlers, you mean normal things like handling keystrokes

DOM handlers are unaffected by this and you can use all the normal stuff like delegation, bubbling, etc. This only affects the synthetic emit system.

> I can imagine multiple views actioning an event; consider that the event is descriptive of what happened rather than what needs to happen. Say, vm.emit("CustomerAddressUpdated") -- multiple vm's will be interested in that fact, say the list view and the detail view if the customer changed is currently selected.

Unless your list view and detail view have an ancestor-decendant relationship, a bubbling event will already not work for you. And that's part of the issue, bibbling is just a neutered pub-sub or event bus system in which you get a bit of clarity as to the order of handler invocation at the cost of only being able to talk "up" to ancestors.

Multiple layers of synthetic event listeners with each layer doing its own thing is eerily similar to the event bus. Of you really want the bubbling, you can "re-emit" the event, similar to re-throwing an exception.

A "CustomerAddressUpdated" may indeed be interesting to multiple consumers but it's more interesting to disjoint consumers than ancestor consumers since presumably they already share a dep-injection heirarchy.

If you don't mind, I'd like an even more specific example of how you envision bubbling being helpful in your CustomerAddressUpdated case and what benefits it would have over an imperative (and restricted) bus/echo chamber. Perhaps with a code example?

**Comment by lawrence-dol** [comment]
> If you don't mind, I'd like an even more specific example of how you envision bubbling being helpful

I've been up all night with no end in sight, so I can't. But, actually, you've made a convincing case for the emit system as it currently is.

**Comment by leeoniya** [comment]
With these changes to the emit system, I'm re-evaluating the usefulness of targeted emit outside of targeted redraw. Before it seemed useful as a "hack" to bypass ancestors which had a matching event handler but you wanted to avoid. It was probably conceived with redraw in mind (to avoid the bubbled redraw-each situation) because I cannot think of why such a convoluted thing would be a good idea otherwise.

There's no reason to remove targeted emit from the functionality while the targeted redraw rides on it, but it's something to consider if this is no longer the case. Yet another reason to remove "emit" from the ancestor-redraw terminology. Perhaps the current `vm.redraw(impCtx = null)` would be better off as `vm.redraw(targ = 0, impCtx = null)` or `vm.redraw(impCtx = null, targ = 0)` and there can simply be a single function for both targeted and untargeted redraw wth no mention or wordier sigs. I'm leaning towards the former sig since mutating `impCtx` would probably be much less frequently needed than requesting ancestor redraw. If the sig is changed, then it would make sense to add an explicit `vm.redrawRoot()` me thinks.

@yosbelms

As I mentioned, the `vm.on()` already facilitates a lot of the "bus" functionality that's restricted to the vm & descendants. The main drawback is that the handlers in the examples are declared in vm itself and not dynamically added by child vms (although this can be considered a good thing for clarity). You could always traverse upwards yourself from a descendant and add more handlers dynamically (there is now a `vm.parent` which is the vm's parent vm). I don't know if it makes sense to provide an "up" locator for this purpose as I don't know yet if this is a pattern I want to encourage. Certainly, it's easy to get this done yourself with your own traversing "up" function in app-space.

**Comment by leeoniya** [comment]
unjailed key prefix has changed from `!` to `^` via https://github.com/leeoniya/domvm/commit/ffdf52a58ee2dd05ae4f21acd4d045705c0509a6 to better reflect the meaning rather than the caveats of using them

**Comment by leeoniya** [comment]
i bit the bullet: https://github.com/leeoniya/domvm/commit/86b2a854c5ff19d993f59f1be2923f83663222f0

- The emit system is now dead simple, no more ancestor targeting
- Ancestor redraw no longer uses the emit system but properly traverses the `vm.parent` chain directly.
- `vm.emit.redraw(targ)` is gone, replaced by `vm.redraw(targ = 0, impCtx)`

I haven't added a shortcut for root redraw that just masks `vm.redraw(1000)`, not sure if needed.

**Comment by leeoniya** [comment]
I'm closing this issue since the original optimization intent of disjoint redraw has been addressed:

```js
vm.up().down('ch2').redraw()
```

You can now use any of the following to achieve the needed results:

- Imperative vms and dep-injection via `impCtx`
- Declarative unjailed `^` keys, `vm.keys.*` and `vm.emit` handlers
- Create your own up/down finders and either trigger manually or attach `vm.on()` handlers from descendant nodes' constructors. Using a common ancestor as a restricted event bus.

Please open new issues to voice any specific outrage.

**Comment by yosbelms** [comment]
@leeoniya

> Looks good. Though on Firefox and Edge the checkboxes look like shit.

That's the standard template by Addy Osmany, submit a patch to [the project](https://github.com/tastejs/todomvc) if you want to improve it.

**Comment by leeoniya** [comment]
> That's the standard template by Addy Osmany

On such an active project? Yikes.

**Comment by leeoniya** [comment]
decided `vm.keys` name was too odd.

unjailed keys (now i'll call them unjailed refs) are just populated into vm.refs as vnodes (like all refs). to get to the vm you'll need to do `vm.refs.myRef.vm`.

all of the following are equivalent

```js
// declarative: the key doubles as an unjailed ref
[MyView, null, "^myRef"]

// in-template: at root view node as the _ref
function MyView(vm) {
  return function() {
    return ["div", {_ref: "^myRef"}, "moo"];
  }
}
```

this uniformity paves the way for unjailed refs of non-root nodes/views.
