### ISSUE TITLE
[Discussion] Replacing render() function by a stream

### ISSUE THREAD

**Issue by jlgrall** [leeoniya/domvm#172]
Related to: https://github.com/leeoniya/domvm/issues/171

I don't know if this would be a possible with the domvm implementation, but from the API viewpoint it looks nice:

```javascript
var View = {
    render: flyd.map(function(state) {
        return el("div", "Data: " + state.data);
    }, stateStream);
};
```

Notice that it prevents the use of the view data, opts and vm, so it only depends on a stateStream defined somewhere else. I am not sure if it is a good pattern for domvm. What do you think ?

**Comment by leeoniya** [comment]
i think the main problem with this pattern is not that render is a stream - that would be easy to hook up - but with streams returning/holding vnodes. once vnodes are returned, they are pre-processed and hooked into the rest of the tree, so not entirely immutable and holds references to the DOM and rest of the vdom structure. there may be a risk of memory leaks with holding some of the "caching" vnodes elsewhere.

i've been battling a phantom DOM node leak in #164 :/

it should be easy enough to hook up and test since domvm supports re-returning the current vnode as a no-change indicator [1].

[1] https://github.com/leeoniya/domvm/blob/3.x-dev/src/view/ViewModel.js#L222-L223

**Comment by leeoniya** [comment]
i'm gonna say no to this. streams should not return anything that's domvm-specific (vnodes, special attrs, hooks, event handlers). there's too much risk of memory leaks here since domvm does not provide its own managed stream impl.
