### ISSUE TITLE
emit semantics

### ISSUE THREAD

**Issue by tropperstyle** [leeoniya/domvm#177]
> Emit is similar to DOM events, but works explicitly within the vdom tree and is user-triggerd. Calling vm.emit(evName, ...args) on a view will trigger an event that bubbles up through the view hierarchy. When an emit listener is matched, it is invoked and the bubbling stops.

This does not seem to work well with explicitly injected views, which is the only use case where I have tried to use this api. It seemed natural to emit an event from within a view, then allow for anyone who has access to the vm instance to be able to subscribe to that event. I guess I was expecting something more like EventEmitter than DOM events.

Calling `vm.config({ onemit: { event() } })` felt clunky anyway so I think I'll add `on` and `off` to `domvm.ViewModel.prototype` in my app, but just wanted to spark a discussion since this was somewhat unexpected for me.

**Comment by leeoniya** [comment]
i think i have the same hangup with multiple emit listeners as with multiple dom event listeners - hard to reason about and unpredictable firing order. i also made a similar choice for lifecycle hooks - you can only have one per type. this is a consistency i'm not eager to break in just a single place.

as for the clunkiness, i decided to move some non-essential stuff under `config` to prevent the api from sprawling and bulldozing user-defined prototype extensions in the future.

i realize that having a pub-sub style event bus could be useful, but as you said it's easy enough to add on/off/signal() yourself, or re-implement emit() as you need.

**Comment by lawrence-dol** [comment]
@tropperstyle : 

> This does not seem to work well with explicitly injected views [...]

What problems are you having with this?

**Comment by lawrence-dol** [comment]
I find the concept useful to decouple stand-alone components from the app. I suppose, in the end, without an event queue, async triggering and multiple listeners, it's not much difference from providing optional callbacks to be invoked by the sub-component.

**Comment by leeoniya** [comment]
determinism is important. very important, imo. you lose that be having an event bus, a queue and async everywhere. you have no idea what will happen, when/if it will happen, and in what order it will happen. it echos the flexibility of monkeypatching, which itself is a workaround for lack of language features, shitty, inflexible or third-party apis.

there's a limit to how much bazaar-style [1] code can exist in an architecture before it becomes 100% fragile COMEFROM [2] spaghetti.

[1] https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar
[2] https://en.wikipedia.org/wiki/COMEFROM

**Comment by lawrence-dol** [comment]
> determinism is important [...] you lose that be having an event bus

To an extent, yes. However, I wasn't suggesting DOMVM should provide an event-bus, but rather musing on the fact that the event emit support might have no more utility than simply providing callbacks for external actions, and, in fact, is less "obvious".

> there's a limit to how much bazaar-style code can exist in an architecture before it becomes 100% fragile

But having designed and implemented highly stable, robust, yet completely event-driven asynchronous real-time communications systems, I can attest that it works when used properly.

Where "properly" means that the asynchronous things properly model reality. When an event is *logically* decoupled from it's effect, it's a prime candidate for being asynchronous. Each async event becomes a logical entry point to a synchronous flow that is abstractly independent of its causal action. In fact, this it a primary factor of all GUI systems. Each user interaction is an async trigger to a synchronous flow, which is independent and very short and limited in its effect. Such systems are imminently easy to reason about, because each flow is so limited and self contained, but, most importantly, the *trigger* is irrelevant.

You are referring, I think, to when event-driven systems are abused by trying to code a procedural action as a series of "events". Doing that is both hard, and confusing... which is why threads were invented, and then subsequently, co-routines. And why JavaScript has worker threads, which have all the benefits of threading, but none of the negatives of cross-thread communications.

**Comment by lawrence-dol** [comment]
Furthermore, on reflection, I don't think that DOMVM or any other JavaScript needs an "eventing" system, since it already has one, at least in the browser, which is the GUI event queue.

**Comment by tropperstyle** [comment]
> What problems are you having with this?

Mainly, you cannot bind multiple listeners.

```javascript
function SomeView(vm) {
  return () =>
    el('#some-view', [
      el('a', { onclick: e => vm.emit('myevent', { my: 'data' } }),
    ]);
};

export default domvm.createView(SomeView);
```

Interested code somewhere else in the app...

```javascript
import someView from 'some-view';

someView.config({
  events: {
    myevent() { /*respond to event*/ }
  }
});
```

Injected views would have the `vm` instance passed to any interested code to call it's api, so it made sense to also bind event listeners, but it does not work, as it will overwrite anything that already exists.

I ended up doing this:

```javascript
Object.assign(domvm.ViewModel.prototype, {
  on(event, fn) {
    this._events = this._events || {};
    if (typeof(event) === 'object') {
      for (let e of Object.keys(event)) {
        this._events[e] = this._events[e] || [];
        this._events[e].push(event[e]);
      }
    } else {
      this._events[event] = this._events[event] || [];
      this._events[event].push(fn);
    }
  },

  off(event, fn) {
    this._events = this._events || {};
    if (event in this._events === false) return;
    this._events[event].splice(this._events[event].indexOf(fn), 1);
  },

  emit(event, ...args) {
    this._events = this._events || {};
    if (event in this._events === false) return;
    for (let i = 0; i < this._events[event].length; i++) {
      this._events[event][i].apply(this, args);
    }
  }
});
```

I have also used a global instance of an event emitter in another project, but I seem to like that the events are scoped to the related UI instance. I agree that maybe events should just be dropped entirely from domvm core.

**Comment by lawrence-dol** [comment]
> I seem to like that the events are scoped to the related UI instance

Actually, that's very valuable, and something that is lost if one uses GUI custom events.

**Comment by leeoniya** [comment]
using custom DOM events also suffers from the problems i outlined. their bubbling can be stopped, so the emitter never knows if they ever reach the needed destination. they can do multiple things at multiple levels in the hierarchy which are hard to reason about, their api is a bit less elegant with the auxiliary data riding on the event object.

the emit system is restrictive for a reason and serves as a quasi-deterministic RPC - bubbling cannot be stopped, it only touches views (not vnodes), it only delivers the payload to a single callback, executes synchronusly and halts.

there's nothing that prevents the use of custom dom events, but since vdom is meant to be a dom abstraction with fewer DOM-isms, i personally prefer custom events to reside in vdom space.

> I agree that maybe events should just be dropped entirely from domvm core.

dunno, i don't see much benefit in removing it, given how few bytes it adds [1]. a nice use-case for it is delegating the handling of actions, without using actual event delegation and keeping the handlers contained without passing everything (eg `list`) down the leaf views.

```js
function List(vm, list) {
  vm.config({
    onemit: {
      deleteItem: id => {
        list.delete(id);
        vm.redraw();
      }
    }
  });

  return (vm, item) =>
    el("ul", list.items.map(item =>
      vw(Item, item)
    ));
}

function Item(vm) {
  function clickDel(id) {
    vm.emit("deleteItem", id);
  }

  return (vm, item) =>
    el("li", {onclick: [clickDel, item.id]}, "X");
}
```

[1] https://github.com/leeoniya/domvm/blob/3.x-dev/src/view/addons/emit.js

**Comment by lawrence-dol** [comment]
Or, just:

    el("li", {onclick: [vm.emit, "deleteItem", item.id]}, "X");

?

That would be a great justification for emit, per my comment that GUI events provide the wrong abstraction and need to be mapped to the intended action.

**Comment by leeoniya** [comment]
oh yeah :)

made possible by the fact that fancy handlers are already called with `this` === `vm`

**Comment by lawrence-dol** [comment]
> made possible by the fact that fancy handlers are already called with `this === vm`

There's just no escaping the damnable `this` in JavaScript!

**Comment by leeoniya** [comment]
@tropperstyle hopefully this discussion has been helpful. i'd like to leave emit as is.
