### ISSUE TITLE
Road to 1.0

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#27]
Road to 1.0
-----------

My hope is to release a stable version by April 1st. This means no further breakage of:

- The published API (Docs)
- Defined behavior (Tests)

There's a lot of work just in the above items for functionality that already exists in the lib. Since I'm currently the only dev, ~~claims of IE9+ compat will have to wait till post-1.0 as I simply have no time to fix everything that might be broken in older browsers and vet all needed polyfills. If anyone cares to help with this, great.~~ IE9+ is done!

Generally, I'm satisfied with the `view` and `html` modules' semantics and performance at this point. However, there's still some significant effort to be put into the `route` and `watch` modules. I'd prefer to stabilize each module indepedently, but this prevents offering a stable concat+min dist build that includes everything. I'm not sure what to do here, but either remove/re-branch some features that are experimental or simply leave them out of the docs; the latter would be simpler, but would bloat the lib size to a small degree to include codepaths that shouldn't run.

**Big-Ticket Items** (besides more tests and docs)

- ~~Hash-based routing interop, query params (https://github.com/leeoniya/domvm/issues/11#issuecomment-186761920)~~ **Done**.
- ~~Prop/attr magic (#18). Maybe needed for 1.0 since it affects ergonomics/expectations. Not sure if this magic should be opt-out or opt-in? If implemented, will need clear and simply-explained behavior plus tests to ensure it doesn't do wonky things.~~ **Done**.

**Small-But-Necessary Items**

- ~~Event handlers can be arrays w/args: {onclick: [cb, arg1...]}~~ **Done**.
- Ponder arguments & order provided to various callbacks and pass-through semantics.
  - ~~view: Event handlers (delegated handlers should also get attachment node)~~ **Done**: `function(arg1..,e, node)` where `arg1..` only appears when using `[cb, arg1..]` style handlers.
  - ~~view: Emit arg pass-through format `vm.emit("myEvent", arg1..)` or `vm.emit("myEvent", args)`~~ **Done**: `vm.emit("myEvent", arg1..)`
  - view: Lifecycle hooks handlers and what's valuable in each case? didMount/willRecycle/etc, `oldNode, newNode`
  - ~~route: handlers (e, arg1..) how should this interop with named querystring params when implemented?~~ **Done**.
  - ~~route: `rt.goto("routeName", args)`, same concerns as above, named vs ordinal? both can exist in URI.~~ **Done**.
  - ~~route: `rt.href("routeName", arg1...)`~~ **Done**.
  - watch: allow setting a context for handlers (vm, vnode?)
  - probably more i've forgotten here

**Maybe Items** (probably post-1.0)

- Third-party lib interop (#7)
  - `{_guard: true}` for nodes
  - `vm.absorb(vnode, el, props)`
  - Accept existing DOM elements in tpl defs (assume guarded?) 
- Optimization channel: allow vtree diff & re-build suppression for known-static trees at both self and children levels. Would just graft the old vtree branch to new.

@lawrence-dol
@yosbelms

**Comment by lawrence-dol** [comment]
First let me say, I am excited by the phrase "a road to version 1.0"; it expresses a commitment to deliver a solid production release.

Second, I am swamped by a task for several international customers that simply refuses to to be "done" to their satisfaction because their expectations were not properly managed. I am on lock-down until I can dig my way out of this hole. 

However, the prototype POC I previously mentioned is next on my plate, and I plan to use the first few days to evaluate whether to use Mithril or DOMVM for it. That will include getting up to speed on docs, playing with it with real but toy code within my specific coding paradigm, and seriously commenting on the semantics and on any cruft I see in the API.

If I like what I see, then my path forward will be to switch to DOMVM for new code and progressively migrate over my Mithril code. The prototype is a for a seriously large and complex app to replace a production Java applet. So the choice matters very much. 

Routes are irrelevant to this app, but they are important to me in general for SPAs (especially for the next big project in the pipeline). Are you able to spell out in a little more detail, with URL examples what is working and where you see it's deficient. My expectation is that given a path after the `#` that the longest matching route will be chosen and it's VM activated; but I am not clear on the interplay between the URL hash-path and the nested VM's. Am I right in thinking of a VM as the logical equivalent of a UI component?

**Comment by leeoniya** [comment]
> ... because their expectations were not properly managed.

"How much for a website?"

> That will include getting up to speed on docs, playing with it with real but toy code within my specific coding paradigm, and seriously commenting on the semantics and on any cruft I see in the API.

Your feedback will be invaluable in catching any gross oversights and serious bugs/omissions. I've been watching numerous vdom libs, ensuring domvm is able to address their shortcomings and missing-but-highly-desired features requested by users without resorting to hacks and with few or zero compromises. Quite a few non-public demos have been written to address many cases.

> Am I right in thinking of a VM as the logical equivalent of a UI component?

Correct.

> Are you able to spell out in a little more detail, with URL examples what is working and where you see it's deficient.

Right now the router is entirely html5-history based and does not handle hashes specifically, nor does it handle querystrings (but will by 1.0). The plan is to add `hash` routing in a format that is identical to the `history` mode. But this would not play well with older browsers where all `history` polyfills rely on using hashes. I think this is a reasonable router caveat and should not prevent uniform implementation. Basically "don't polyfill history in older browsers if you intend to use hashes". More in #11.

> My expectation is that given a path after the # that the longest matching route will be chosen and it's VM activated; but I am not clear on the interplay between the URL hash-path and the nested VM's.

There is no built-in view-router coupling. The router is just a route list w/ param defs that hooks `window.onpopstate` (and soon `window.onhashchange`) and invokes `onenter` and `onexit` callbacks of the matched routes. It has a reverse-routing api that allows you to generate `hrefs` and `onclick` handlers from the declared routes for use in your templates. What you do in the route handlers, how you save/restore view or sub-view states, what you redraw or not is completely up to you. The routing event `e` has some helpful info as to where you're about to go (in onexit) or where you're coming from (in onenter), but for now that's about it and I don't expect to add too much more to it.

Your best bet is to look through the ~220 LOC implementation of http://domvm.threaditjs.com/. It's lives on a server configured to serve up `index.html` regardless of url, so operates as an SPA which handles server errors, etc. If it seems slow, it's because the server intentionally randomly fails and throttles requests. Look in the console for actual render timings/network requests and perf.

**Comment by leeoniya** [comment]
IE9+ now pass all tests as of 9247b4c2e7c07dc364b5b99ac60d91ec4a6eb8f7 \o/

**Comment by lawrence-dol** [comment]
Well done! Do you have a list of shims required for IE versions? I assume that DOMVM runs on current evergreen browsers without shims... or am I mistaken? I am *almost* about to start my next project, for which I am evaluating DOMVM.

**Comment by leeoniya** [comment]
@lawrence-dol

> Do you have a list of shims required for IE versions?

Shims are documented and provided in the repo: https://github.com/leeoniya/domvm#features

> I assume that DOMVM runs on current evergreen browsers without shims

Yes, except `fetch` must still be shimmed in some cases (Edge, Android Browser, Safari?) as it's fairly new. This doesn't apply if not using the `watch` module. The core `view` only needs `rAF` and ES6 `Promise` shims.

**Comment by leeoniya** [comment]
I should mention I only ran the IE9+ tests on Windows 10 x64 in IE11's emulated modes. Sometimes there are inconsistencies between those and the real deal, but it should be good 'nuff for 1.0.

**Comment by leeoniya** [comment]
updated todo for myself:

**Tests**

- `route` module
- `watch` module
- `view` module
  - lifecycle hooks (shallow/deep)
  - isomorphism - maybe monkey-patch `mount()` so all existing tests can be re-run isomorphically?
  - domvm.view.extend - vm monkey-patching
  - vm.patch - this method isn't really vm-dependent, could be moved to util

**Docs** (besides what's already listed in unfinished README outline)

- explain model persistence, handle/key effects on recycling
- vm.update(newModel)
- vm.unmount
- route replace instead of push
- route handler params
- watch module
  - prop
	- async prop
	- mutate, prevent fire()
  - sync
    - prevent fire()
  - get/post/put
  - fire()

**Node**

- Verfiy `html`/SSR still works
- Publish 1.0 package

**Comment by leeoniya** [comment]
@lawrence-dol 

curated polyfills now live in https://github.com/leeoniya/domvm/tree/master/src/polyfills

concat & min version now available in /dist: https://github.com/leeoniya/domvm/blob/master/dist/polyfills.min.js

**Comment by leeoniya** [comment]
I've decided to postpone the completion of docs and tests till after 1.0. Hopefully i will get some help with these ;)

IMO there is an adequate combination of tests, benches plus feature-focused, non-trivial demos, such that their bug-free operation is a sufficient vote of confidence for 1.0. The API churn has settled at this point and aside from catching up `watch.sync` and re-validating Node/isomorphism, everything is in place for API freeze.

Another thing that won't be fully tested is that all *demos* work flawlessly in all browsers. Polyfills/shims are not perfect and sometimes the way rAF queues and Promise resolution works is wonky. I will only validate that demos work in the latest browsers w/polyfills along will all core tests passing in IE9+.

**Comment by lawrence-dol** [comment]
> I've decided to postpone the completion of docs and tests till after 1.0. Hopefully i will get some help with these ;)

I think that's a good call.

> ... along will all core tests passing in IE9+

Since all versions of IE before 11 ceased support from MS as of Feb this year, and even IE 11 is only on life-support, that seems quite reasonable. But I appreciate the support for IE9+ for my current project where it's harder to require the customer to use only evergreen browsers. 

However, even in this case, since I'm replacing a *big* Java applet, we're making EB's to within 12 months old as one of the primary minimal requirements. Current plan is to officially support Chrome, Firefox, Safari (the thorn in my side) and Edge and with respect to IE say, "if it works good, if it doesn't c'est la vie".

But, in the end, the customer is always right, so we may be forced to support IE 9 to 11. I really hope Microsoft goes EB with Edge soon.

I do hope that DOMVM is able to avoid chasing the rainbow with shims once ES6 becomes mainstream, though for exactly the reason you said,

> Polyfills/shims are not perfect.

Broken shims put users of DOMVM at a disadvantage with their customers because effectively we have to support the shims as well when they are broken. They're fine for the "unsupported" browsers, but can be a big pain for the ones we officially (contractually) support. I prefer, as much as possible, to do without things that aren't directly supported by the browsers.

**Comment by iamjohnlong** [comment]
I will hopefully have some free time to help with docs in the next week or two. I have a large project due in three days plus I'm in the process of moving from Utah to Idaho. FYI this lib is rad and I'm super stoke on it.

**Comment by leeoniya** [comment]
@lawrence-dol 

> Since all versions of IE before 11 ceased support from MS as of Feb this year, and even IE 11 is only on life-support, that seems quite reasonable.

unfortunately, this is meaningless for most practical purposes. domvm is not a library just for internal apps where you can dictate the env. IE9 is alive an well in the real world and if you're spending good money on ads to get eyeballs to your site, then showing even 10% of visitors a middle finger is a non-starter.

we even see orders placed from IE8 on old Windows Media Center PCs that never update (shudder). but really, how often do you update the equivalent of a kiosk/dvd player? it's sad, but i get it :/

> a big pain for the ones we officially (contractually) support

we officially support none. there are some bundled for convenience which are known to not cause test failures (for the current set of tests). it saves people the effort and at least creates a common ground for reporting compat issues and finding better polyfills.

**Comment by leeoniya** [comment]
@iamjohnlong , thanks! good luck with the move.

**Comment by leeoniya** [comment]
1.0 has been tagged and published to npm

**Comment by lawrence-dol** [comment]
Nice!

**Comment by iamjohnlong** [comment]
:facepunch: Good work sir!
