### ISSUE TITLE
Coerce non-renderable values?

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#4]
What to do if a node or value is any of the following (or a getter/promise that returns them)?

```js
[], null, false, true, undefined, NaN, Infinity, {}, {a:6},
```

Right now there's just breakage, usually when these values hit the DOM operations that throw errors when the parameters they expect don't match.

While these can be avoided, they sometimes show up at runtime as a result of doing inline computation within the template or creating children by mapping an empty result array, etc. Ideally, these cases should be handled outside domvm but it makes the templates much dirtier/boilerplatey. If domvm handled these situations, there would be a lot of overhead in checking all these cases as it would need to be done on every `.redraw()` for:

- Each node itself
- Each prop/attr/event value
- Each css prop value

Second, it's not clear what should be done. Coerce them all to empty strings? Splice them all out? Insert placeholder comment nodes and `.replaceChild()` if they morph to something renderable?

A related issue is isomorphism and what to do about empty text nodes WRT the strategy above? Squash empty text nodes since they cannot be accounted for in `innerHTML` (as is done now)? Insert comment nodes as placeholders?

As for coercion, probably the best option is to simply assist in debugging these issues at dev time? The DOM instrumentation helper in `test/lib/dominstr.js` can be used to wrap try/catch around these DOM ops and barf out more useful info like the params. Or maybe provide a debug build that has try/catch integrated and can barf out the actual template node info, etc?

**Comment by lawrence-dol** [comment]
I'm mostly lurking, but my response is:

  [] => blank node / value
  null, undefined => node omitted or "" for a value.
  false, true "undefined", NaN,  => "false", "true"
  NaN, Infinity => "undefined", "NaN", "Infinity"
  {}, {a:6} => toString()

In other words, most bad values simply show the string equivalent. And null, undefined is easily and cheaply checked.

**Comment by leeoniya** [comment]
hey @lawrence-dol , thanks for lurking.

So here's what I'm thinking

1. `[]`,`null`,`undefined` => remove node
2. `{}`,`{a:6}` => .toString()
3. `true`,`false`,`NaN`,`Infinity` => ""+value

1. The first case will require 3 extra checks since isArr() already runs as part of normal processing to discern tags from sub-views and and sub-arrays. https://github.com/leeoniya/domvm/blob/master/src/domvm.js#L335
	```js
	if (node === null || typeof node === "undefined")
		// splice out
	else if (isArr(val)) {
		if (!val.length)
			// splice out
		else
			...
	}
	```
2. The second case should not require any overhead since isObj() runs as part of normal processing to grab Promises and pre-inited vms. https://github.com/leeoniya/domvm/blob/master/src/domvm.js#L343

3. The third case can live in a final else.

**Comment by lawrence-dol** [comment]
`node == null` will cover undefined. 

-- 
Lawrence Dol
http://think.dolhub.com/
http://tech.dolhub.com/
(Sent from my phone)

On Jan 15, 2016, at 08:36, Leon Sorokin <notifications@github.com> wrote:

hey @lawrence-dol , thanks for lurking.

So here's what I'm thinking

[],null,undefined => remove node
{},{a:6} => .toString()
true,false,NaN,Infinity => ""+value

The first case will require 3 extra checks since isArr() already runs as part of normal processing to discern tags from sub-views and and sub-arrays. https://github.com/leeoniya/domvm/blob/master/src/domvm.js#L335

if (node === null || typeof node === "undefined")
    // splice out
else if (isArr(val)) {
    if (!val.length)
        // splice out
    else
        ...
}
The second case should not require any overhead since isObj() runs as part of normal processing to grab Promises and pre-inited vms. https://github.com/leeoniya/domvm/blob/master/src/domvm.js#L343

The third case can live in a final else.

**Comment by leeoniya** [comment]
oh, good. thanks!

**Comment by leeoniya** [comment]
implemented!

thanks for your help.

**Comment by leeoniya** [comment]
To clarify, it's implemented for nodes/bodies, but *not* attr/prop/style values. The logic for values is different (and much more straightforward). However, I dont know if coercing those is as necessary, i think there's less weirdness there and typically you'll only every be setting a string, number or a getter returning one of those.

**Comment by lawrence-dol** [comment]
FWIW, I'd write it as:
      
          if (node == null || (isArr(val) && !val.length)) {
                // splice out
            }
            else {
                ...
            }
      
      You might even get away with treating anything with a zero
        `length` property as empty:
      
          if (node == null || !val.length) {
                // splice out
            }
            else {
                ...
            }
      
      (Though without more context it seems like `val` should be
        `node`.)
      
      
        -- 
        Lawrence Dol
        http://think.dolhub.com | http://tech.dolhub.com

**Comment by leeoniya** [comment]
@lawrence-dol 

the actual commit is different than what's above, btw. it's structured in multi-level if/else's so that adding other node types is easy in the future. it's a bit longer than grouping the conditions (as they were before this) but much more clear/maintainable. I also avoid doing some ops twice that i was doing previously like `isArr()`.

@trueadm

Checkout these tests: https://github.com/leeoniya/domvm/blob/5c6c103c779a1bd88372d1b0501dc447515bd72f/test/tests.js#L1252

I think they address your concern in https://github.com/trueadm/inferno/commit/134a90005cc8a3900bd601666dd1aa474c0abb6f#commitcomment-15450964 about merged text nodes morphing types between redraws.

**Comment by lawrence-dol** [comment]
Fair enough. 

If I may offer a little advice, I would say to write code as the clearest and most succinct expression of the logic as it is right now, rather than making allowances for what the logic might be tomorrow. Clarity and brevity are often competing goals and require balance, but both are important, the former moreso than the latter. 

-- 
Lawrence Dol
http://think.dolhub.com/
http://tech.dolhub.com/
(Sent from my phone)

On Jan 15, 2016, at 11:03, Leon Sorokin <notifications@github.com> wrote:

@lawrence-dol

the actual commit is different than what's above, btw. it's structured in multi-level if/else's so that adding other node types is easy in the future. it's a bit longer than grouping the conditions (as they were before this) but much more clear/maintainable. I also avoid doing some ops twice that i was doing previously like isArr().

@trueadm

Checkout these tests: https://github.com/leeoniya/domvm/blob/5c6c103c779a1bd88372d1b0501dc447515bd72f/test/tests.js#L1252

I think they address your concern in trueadm/inferno@134a900#commitcomment-15450964 about merged text nodes morphing types between redraws.

**Comment by leeoniya** [comment]
I made it as brief as it can be without having to call functions twice or repeating conditions in various permutations in different places. For example, I would rewrite and nest stuff like this all day long:

```js
if (def2IsObj && someThing1 && someThing2) {
}
else if (def2IsObj && !someThing1 && someThing2 && someThing3) {
}
```

If you look at domvm code and have some specific suggestions, please let me know. Otherwise let's not get into a philosophical discussion, there's way too much to do without it :)

Also, there was about a 4% perf regression within the last couple commits which both handle some form of text-node merging, either for isomorphism or for this bad value squashing. May have been worth it, but also need to check that nothing stupid is being done to cause this for no reason.

**Comment by lawrence-dol** [comment]
@leeoniya : In the context of the code it makes much more sense (but is orthoganal to what I said; you said you wrote it the way it was to make adding future conditions easier, not to fit with current conditions today).

So what's the work-around / return for nodes that are sometimes blank sometimes not for when they are blank to keep the vDOM tree matched up? Return `[ "" ]`?

**Comment by leeoniya** [comment]
i just pushed a commit that always removes empty text nodes. this solves some issues with inter-tag empty text for isomorphism/html. it also removes some code that was in place to faux-insert them during attach().

i'm not sure i understand your question. can you provide a more concrete example with 2 full templates? maybe before/after mutation?

**Comment by leeoniya** [comment]
if you dont touch the DOM (aside from attrs/props not managed by the templates) and only use vm.redraw(), the vtree is guaranteed to be in sync.

i plan on adding a `vm.absorb()` so any managed properties that were mutated externally [maybe by some third party lib] can be resynced back into the vtree and continue to happily chug along.

**Comment by lawrence-dol** [comment]
I meant avoiding the problem where dropping one node in a long list causes all subsequent nodes to be rebuilt.

**Comment by leeoniya** [comment]
again, what do you mean by "rebuilt"? the dom is reused if possible but the only dom operation that happens is a single `removeChild`, like you would do if you did it manually.

**Comment by lawrence-dol** [comment]
Not talking about the remove; that's easy. I'm talking about all the subsequent nodes that then get rebuilt because the don't match anymore. For example:

    <div>... this is a popup ...</div>
    <div>... this is the entire UI ...</div>

Mithril has (had?) a thing to be aware of whereby omitting or including the popup `div` would have the consequence of rebuilding the UI `div` since the two `div` tags appear(ed) undifferentiated to the differencing logic. The solution was to use keys or to not remove the popup `div` altogether but instead leave it empty:

    <div></div>
    <div>... this is the entire UI ...</div>

I realize this is a little vague, but I am just wondering how `domvm` deals with this (it's directly relevant to where null/undefined/[] indicate a node should be dropped altogether.

**Comment by leeoniya** [comment]
no, it's not vague. domvm is similar, but not identical.

open your console and click some list items to remove them. the instrumentor will show you which dom ops happen: https://jsfiddle.net/hczp387b/2/

in this case, since the list is uniform, there is no full rebuild, but the subsequent `nodeValue`s get updated to match the values. similarly, it can be avoided by just adding a key: https://jsfiddle.net/hczp387b/3/

another way to avoid it is to have persistent model objects and each item to be a sub-view that links its model, that way you dont need keys.

if you think about it, this is the only way it could work since there is no way to determine from 2 different arrays whether several things have been removed or there have just been massive changes to the data or ordering. exhaustively checking this is very impractical and much slower than simply updating the subsequent nodes to match.

you can check the timing for yourself in the console on a list of 1000 items, remove the first one. faster with keys, but still plenty fast without. i dunno how Mithril performs, but...

1000 with keys: https://jsfiddle.net/hczp387b/4/
1000 no keys: https://jsfiddle.net/hczp387b/5/

**Comment by leeoniya** [comment]
another easy way to avoid reuse, it to nest the popup itself another layer.

```
<div><div>... this is a popup ...</div></div>
<div>... this is the entire UI ...</div>
```

or order it after the UI:

```
<div>... this is the entire UI ...</div>
<div>... this is a popup ...</div>
```

or hide it with css:

```
<div style="display: none;">... this is a popup ...</div>
<div>... this is the entire UI ...</div>
```

there are about a million options. but as with other libs, if you insist on having the entire expensive ui and the popup be sibling nodes (pretty odd, tbh), and the popup can vanish, then just place it later in the DOM.
