### ISSUE TITLE
Mental model of `vm`.

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#40]
Forgive me if this is already documented, but would you be able to give a one or two paragraph description of what the `vm` thing is? I realize it stands for "view-model", but it's not the expected context object in which I store my view's model data and it's clearly not the data model, which is given as the second argument; rather it's a concept specific to DOMVM. I would almost venture to say it's the view's API to domvm, except that what I thought domvm.view was.

**Comment by leeoniya** [comment]
it is the model of your view (the materialized template that is backed by the dom). it's your api to the dom which can hold state, private methods and expose view api methods via `vm.api.*`

views are not, however, meant to *be* your models, but should serve as stateful window(s) into them. however, as you can see from the docs (usage patterns) the vm+init closure may be [ab]used as such to an extent.

**Comment by leeoniya** [comment]
your view's init closure serves as the link between the view/template/dom and the passed-in model.

does any of this help clarify things?

**Comment by leeoniya** [comment]
another thing that the `vm` does is give you a persistent, refreshable handle into a branch of the virtual tree that's used to regenerate the dom.

**Comment by leeoniya** [comment]
there is nothing about the vm that pertains to your domain models, except one thing: if you provide it with a persistent domain model, it will "stick" to it, so to speak.

**Comment by leeoniya** [comment]
look at the TodoMVC implementation in /demos.

the models/app is almost entirely decoupled from the domvm views. the models have existing apis and the views are simply providing a ui interface for the model's state and for invoking the model's methods.

it is a fully decoupled view layer to an existing app.

**Comment by lawrence-dol** [comment]
I am chewing on this; thanks.

So the part of `vm` that holds my model state is `api`? I think I'd have rather called it `ctx`. But I'm still chewing.

**Comment by lawrence-dol** [comment]
> it is the model of your view (the materialized template that is backed by the dom)

Except that if I inspect the object, it bears no resemblance at all to my template and it's available before my template has been even generated?

**Comment by leeoniya** [comment]
> So the part of vm that holds my model state is api? I think I'd have rather called it ctx. But I'm still chewing.

the vm holds no model state. it holds view state. you can think of it as mearly holding a pointer to the model you provide it. in this way it is loosly linked to the model.

> Except that if I inspect the object, it bears no resemblance at all to my template and it's available before my template has been even generated?

the vtree is a heirarchy of vnodes which exactly resemble your templates. those nodes which are vm/view roots have a `node.vm` property and the vm itself has a circular reference back into the tree via `vm.node`.

**Comment by lawrence-dol** [comment]
Okay, that helps some. I'll sleep on it. I'm one of those people that has to get the conceptual model right to build on it. I have to understand where the "puzzle pieces fit".

When I said, "the part of vm that holds my model state is api?" I meant the view's model/state, not the domain model. I find it unnatural to access state via, for example, "vm.api.isExpanded"; perhaps because I've never liked non-private mutable properties and "api" implies to me something generally available to other parts of the code -- that is, the exposed interface.

**Comment by leeoniya** [comment]
> "api" implies to me something generally available to other parts of the code -- that is, the exposed interface.

That's precisely what it is for. vm.api is there for you to use *if* you want to expose the view state or view methods to the outside world.

Here's a basic example: https://jsfiddle.net/unvjt7tu/2/ explained below...

Let's start with a simple instance of some `List` domain model with a simple API. No domvm, no views, just data:

```js
// model def
function List(items) {
	this.items = items;
}

List.prototype = {
	add: function(item) {
		this.items.push(item)
	},
	remove: function(idx) {
		this.items.splice(idx, 1);
	}
};

// model instance
var myList = new List([
	{id: 100, text: "Hello"},
	{id: 200, text: "World"},
]);
```

We take the model instance `myList ` and create an external view of it which simply operates on the model's existing API and exposed state. In addition, the view has its *own* state to hold the selection list and its *own* exposed api so that we can operate on the view programmatically as well as via input devices. This allows us to automate the view, if needed.

```js
// view def / init closure
function ListView(vm, list) {
	// private view state (list of selected items)
	var selected = {};
	
	// exposed view api allows interaction with this view programmatically
	// and also used as event handlers in the returned template
	vm.api = {
		toggleSelect: function(id) {
			selected[id] = !selected[id];
			vm.redraw();
		},
		deselectAll: function() {
			selected = {};
			vm.redraw();
		},
	};
	
	// private handler for invoking list's "remove" & invoking view's redraw
	function remItemAndRedraw(idx) {
		list.remove(idx);
		vm.redraw();
	}
	
	// render()
	return function() {
		return ["ul", list.items.map(function(item, idx) {
			return ["li" + (selected[item.id] ? ".selected" : ""), {onclick: [vm.api.toggleSelect, item.id]},
				["button", {onclick: [remItemAndRedraw, idx]}, "X"],
				item.text,
			];
		})];
	};
}

var myListView = domvm.view(ListView, myList).mount(document.body);
```

Now we can also invoke the view's api programmatically:

```js
// programatically invoke the view's same toggleSelect
// method as used by the bound DOM handlers
setTimeout(function() {
	myListView.api.toggleSelect(200);
}, 1500);
```

**Comment by leeoniya** [comment]
You can make a dozen decoupled views of this same model and each of these views can be inserted into into some larger view of the full app into disjoint DOM locations. This has the fantastic property of creating multi-view components, where state is shared (such as a shared model), but the DOM hierarchy does not need to be shared.

**Comment by lawrence-dol** [comment]
That all makes total sense. The stumbling block for me is that "view-model" doesn't convey that to me. In fact, the term view-model conveys to me the dynamic *state* needed by the view, not the API to manipulate it. In other words the view-model would always be private. But that makes me want to attach data to `vm` rather than `vm.api`. Is this because my conceptual understanding of a view-model is wrong? 

I confess that in 34 years of programming I've never fully grasped the concept and value of MVC or it's derivatives; my mind naturally gravitates instead to component-oriented UI with the data-model self-contained or injected (like Java's Swing). I've even implemented a full GUI toolkit for Java based on "turtles all the way down" composable components which I found incredibly easy to reason about, use and extend. That said, your example makes perfect sense, though I see it as a component + model more than view-model + data-model. 

Maybe this is merely a terminology problem. I remember when I first came to Java I was hard pressed for several months until the OO terminology just clicked one day; it was then I realized that I'd been programming OO in C for many years, only with manual allocation and release. After that I took to OO like a duck to water.

I am tempted to change the name of the `vm` argument in my code to `cpt` (component). Would that be wrong or misleading in the long term?

BTW, thanks for being incredibly patient with me on stuff like this -- I know it can be frustrating when someone doesn't get the seemingly obvious. I hope to be able to adopt DOMVM across the board and repay you in documentation and in honing the code.

**Comment by leeoniya** [comment]
> I am tempted to change the name of the `vm` argument in my code to `cpt` (component)

sure, whatever makes sense to you. the `vm` is the lib's api (and internal state) to the yet-to-be-created vtree node from the returned template's root.

i agree that it's a bit strange that your app-space exposed view api (if you have one) must piggyback on the lib's internal api (vm) via `vm.api`. there might be a different way to structure things, but i wanted to have shallow access to critical lib methods like `vm.redraw()` without introducing a wrapping object like `{libApi: vm, yourMethod1:...}`, since the calling convention then becomes `myComponent.libApi.redraw()`.

probably the best alternative name for it is `vapi`. but again, it's hard to categorize it neatly in terms of existing concepts. it's linked to both the passed-in domain model (by default) and the init closure state. it walks like an instance and quacks almost like an instance. you can almost think of it as if each of your view definitions extends some higher-level class in OO and you can add or replace methods in it at-will. some totally broken pseudo-OO:

```
class ViewComponent(model, key) {
   public node;
   public function mount() {...}
   public function redraw() {...}

  // some init code
}

class MyView extends ViewComponent {
  ...
}

vm = new MyView(someModel);
```

happy to help, the better you understand, the better you can make meaningful suggestions and properly explain it to others.

**Comment by leeoniya** [comment]
In the end, i think View Model is consistent with the original meaning [1].

It provides a stateful abstraction layer, binding and api between your domain models and your raw template definitions.

[1] https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel

**Comment by lawrence-dol** [comment]
This is enough said, I think; mark this to revisit for documentation.

**Comment by leeoniya** [comment]
added

**Comment by franzliedke** [comment]
Sorry for hijacking an already closed issue...

I just read the Wikipedia article you linked to, @leeoniya. One question that occurred to me: the state of the `vm` object - is that in any way connected to the model, or is it only state of the view object itself? In the latter case, wouldn't that mean it is much closer to implementing the "view" layer than the "view-model"? Citing from Wikipedia here:

> The view model has been described as a state of the data in the model.

**Comment by leeoniya** [comment]
> Sorry for hijacking an already closed issue...

it's not hijacking if it's on-topic :)

> the state of the vm object - is that in any way connected to the model, or is it only state of the view object itself?

the vm object is only connected to the model (by default) for internal diffing purposes, similar to a "key". for an example with nested views:

```js
var items = [
	{text: "a"},
	{text: "b"},
];

function ListView(vm, items) {
	return function() {
		return ["ul", items.map(function(item) {
			return [ItemView, item];
		})];
	};
}

function ItemView(vm, item) {
	return function() {
		return ["li", item.text];
	};
}

var listView = domvm.view(ListView, list).mount(document.body);

// reverse sort
items.sort(function(a, b){
	return b.text.localeCompare(a.text)
});

listView.redraw();
```

What happens is that the each initialized ItemView is "bound" to the passed-in model. When the model is persistent but moves among siblings (like during sorting), the DOM/view state will follow it. Rather than simply re-using the nodes, the DOM gets detached and reordered. So the `vm` is a persistent api to the same underlying DOM, this is important for things like CSS animations, etc.

This is the same as providing a consistent `key` to the sub-component. And you can also do that in domvm: `[ItemView, item, "itemA"]`

You can opt out of any implicit binding (aka assumption of model persistence) by providing `false` for the key/handle: `[ItemView, item, false]`. This allows for full DOM recycling upon model deletion, etc.

Aside from this, since the model is passed into the init constructor, it's bound to the view state in this way by the nature of the language because it's not in the scope and is is an immutable reference to it.

> The view model has been described as a state of the data in the model.

This quote is a poor choice of excerpt from the original article [1]. The article as well as the original concept comes from WPF land, from a different language and separation concepts. From that article, I would instead use:

> The ViewModel is a "made for UI" object that represents the Business Object.

The graphic from the wiki [2] is a good illustration of what the concept is. In my mind, the View is the DOM, the ViewModel is the ui component that has its own state and api which abstracts the DOM and contains the template/logic to regenerate it. The domain Model is simply injected into the ViewModel, which then proxies DOM interactions and (view api calls) to the domain model and domain model's state back to the DOM. You can have multiple ViewModels for a single model, each is completely independent of the others unless you choose to wire them together.

I think there's actually less ambiguity here vs MVC and how the "C" translates to the UI. Everyone has their own concepts of what should be in the Controller [once the server is removed from the picture].

In domvm, the ViewModel is really the pair: init closure + vm (native api to the vtree branch)

[1] http://wayback.archive.org/web/20080201101909/http://www.acceptedeclectic.com/2008/01/model-view-viewmodel-pattern-for-wpf.html
[2] https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel#/media/File:MVVMPattern.png

**Comment by leeoniya** [comment]
I should also point out that in the graphic, how those arrows are arranged (data flow an interaction) is entirely up to you and how much wiring/mutation observers you want to set up. Hence the multitude of possible patterns [1]. You can choose to nest these layers, decouple them, make the domain model view-aware, etc. Javascript is so flexible that you can nearly always choose the design pattern that has the most useful trade-offs / coupling for any particular app without having to deal with pre-determined tradeoffs & work-arounds from a more rigid framework.

[1] https://github.com/leeoniya/domvm#subviews-components-patterns

**Comment by lawrence-dol** [comment]
> In my mind, the View is the DOM, the ViewModel is the ui component that has its own state and api which abstracts the DOM and contains the template/logic to regenerate it.

But wouldn't this mean that the function called the "view" and that returned from it are themselves part of the view-model. Meaning that conceptually, the injected `vm`, plus the `view` closure, plus the returned `render` function, plus any logical/mapping in any of these things are altogether the `view-model`, and not any one of them? Making the naming of the `vm` parameter misleading?

I instinctively click with the render function returning a model of the view (where the resulting DOM *is* the view) and that therefore the things that work together to enable the render output are themselves part of the view-model. 

If true, this helps me greatly. But it also reinforces my desire to name the `vm` argument something else (perhaps `dva` for "DOMVM API" or "DOMVM Access").

Meaning, all of the bits in the following code are a "view model":

````
function indicatorView(cvm,mdl) {
    var clkfnc;

    if(mdl.mode=="T" || (mdl.mode=="A" && !mdl.value()) || (mdl.mode=="D" && mdl.value())) {
        clkfnc=function() {
            cvm.emit("toggleMode",mdl.idn,mdl.value());
            return false;
            }
        }

    return function render() {
        return [
            "div.indicator."+mdl.idn+""+(mdl.value() ? ".on" : ".off")+(mdl.mode=="T" ? ".toggle" : mdl.mode=="A" ? ".activate" : ".deactivate"),
            { onclick: (clkfnc ? clkfnc : NOP) },
            mdl.text,
            ];
        }
    }
````

**Comment by leeoniya** [comment]
yes, all of this is correct.

i suppose the reason i chose to call it vm is because from a *consumption* perspective it's your only handle and api to the constructed ViewModel, since the rest is inaccessible. However, from a *construction* perspective (and internally in the init closure), it's one of the multiple accessible pieces to you, but it *is* in fact the same object, just in different stages of initialization.

because it is the same object, i want uniform internal and external naming. and from the outside it represents your viewmodel instance, so i chose "vm".

**Comment by leeoniya** [comment]
again, feel free to name it whatever makes sense to you. none of the api actually relies on "vm" naming (unless you start walking the vtree and hacking the internals)

**Comment by lawrence-dol** [comment]
Thanks; I feel like someone just turned up the dimmer switch. :-)

**Comment by leeoniya** [comment]
also, calling it "domvm's api" is accurate only until you decide you want to expose your own `vm.api`, then suddenly it's domvm's API + your api.

keeping it `vm`, leaves it ambiguous enough so you're not calling `domvmapi.api.*` for your own methods.

my $0.02
