### ISSUE TITLE
DOMVM Discuss

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#46]
Would it make sense to create a domvm-discuss repo just for separating out discussion around DOMVM? Meaning opening issues there as topics for discussion, even closing them when the topic has reached a logical conclusion.

**Comment by leeoniya** [comment]
it makes it impossible to easily reference/tag issues from commits. also, there would be less exposure, since no one will watch that repo except for you. i would rather people freely chime in if they see some topic of discussion that strikes a note with them.

what would be the benefit? some pipe-dream of 0 issues in the main repo? ;)

**Comment by lawrence-dol** [comment]
> what would be the benefit? some pipe-dream of 0 issues in the main repo?

No, separating issues with DOMVM from discussion about DOVM. Not about changes or issues with DOMVM, but using DOMVM. Fostering community interaction. Rather like Mithril uses Google Groups and/or Gitter (both of which I detest). In the same vein as separating domvm-widgets from domvm.

Otherwise, after a while salient things get lost in the noise. It just happens that GitHub's issue system is highly usable, aesthetically pleasing, and interacts well with email.

It's just an idea; not necessarily a good one. If you're happy to use the main repo for that then so am I.

**Comment by leeoniya** [comment]
At some point most things turn into "Let's move this to Gitter". I personally don't like this either. A forum is better and can be referenced by others in the future. splitting the discussion into another repo is an even deeper level of creative abuse of github's platform. let's keep things here for now and just keep stuff organized via labels. if/when the discussions pick up speed, we'll switch to a better format.

domvm-widgets is its own repo because i want its *source* and git log to be separate from the core, as well as versioning, contributor permissions, etc.

**Comment by franzliedke** [comment]
Just FYI, if you ever decide to actually do this:

> it makes it impossible to easily reference/tag issues from commits

This is actually possible. `leeoniya/domvm-widgets#1` creates leeoniya/domvm-widgets#1 :).

**Comment by leeoniya** [comment]
yeah, thx. i suspected it could be done this way :) i don't think a discussion-only repo is a good idea, but in other cross-repo cases, will definitely use when needed

**Comment by lawrence-dol** [comment]
> What would be the benefit? some pipe-dream of 0 issues in the main repo? ;)

Actually, in one sense this should be plausible. Eventually, hopefully quite quickly, DOMVM should stabilize, and the only real issues should be the occasional performance tweak and the adoption of better idioms as they become mainstream. Everything else should be in the periphery in domvm-widgets, with perhaps the occasional new optional module for things applicable to a broad class of apps.

**Comment by leeoniya** [comment]
stabilization does not imply completion. jquery is still fixing bugs in years-old features. there will always be bugs.

1.0 simply means that a measly 4 thousand lines of testing code and demos [which i foolishly consider to cover 85% of use-cases] has not hit any of them.

domvm-widgets is an even peskier minefield.
