### ISSUE TITLE
Multiple ref names?

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#66]
Have you ever considered allowing multiple ref names. So I could have:

    _ref: [ "field1", "firstField" ]

    ...

    _ref: [ "field23", "lastField" ]

Right now I have to do a somewhat clumsier:

    if     (fld.isFirst && fld.isLast) { ref="onlyField";  }
    else if(fld.isFirst              ) { ref="firstField"; }
    else if(               fld.isLast) { ref="lastField";  }

since when there is only one input it's both the first and last field.

**Comment by leeoniya** [comment]
since refs also double as keys in the absence of _key it would require some additional code changes. the fact that refs can be exposed and also namespaced makes this proposal creep in the amount of code needed to handle it.

i don't think this case is gonna be common and you can always make a helper func that gives you the correct refName after accepting some prefix and childCount as args.

gonna say no to this one.

**Comment by lawrence-dol** [comment]
Fair enough.
