### ISSUE TITLE
[router] deprecate useHist & root; replace with prefix: "#"

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#79]
rather than two opts, having one is clearer.

`prefix: "#"` - uses hash (default)
`prefix: "#/myapp"` - uses hash with a root
`prefix: "/myapp"` - uses history API with root

idea borrowed from Mithril rewrite ;)

**Comment by lawrence-dol** [comment]
Good idea; I like it.

**Comment by leeoniya** [comment]
This brings up an additional 2 questions.

1. If you want to use the history API with and the app lives in the root, `prefix: "/"` would mean that all paths in route definitions would have to be slash-free. Otherwise the has definition would also need to be `prefix: "#/"`.
2. Semver. Since this would be a BC break, technically it should be a 2.x change. Since domvm is versioned as a bundle rather than by module, it creates a crappy situation. I also don't want to deprecate the code with warnings in 1.x because that code will bloat the codebase for some time, since 2.x is not on the radar. An alternative strategy could be a 1.x release that hangs around for a couple months with warnings and another 1.x release that makes the switch. 2.x could instead be the migration to by-module semver.

What do you guys think?

@lawrence-dol @yosbelms

**Comment by tamasnet** [comment]
What if `prefix: "/"` just triggers history mode but actually sets the prefix to blank?

Or, alternately, what if history mode ignores leading slashes on route paths?

**Comment by lawrence-dol** [comment]
> would mean that all paths in route definitions would have to be slash-free

I assume you mean "... have to be *leading* slash free"? Could not `prefix: ""` work? I've run into that problem many time before with "pathy" things, and there's no intuitive way to do it because `/` is a path with a trailing separator and `/abc` is one without. You could use `/abc/` for consistency, but that would be an app level choice.

**Comment by lawrence-dol** [comment]
> Semver

I think with semantic versioning, which is probably useful in a library, you either have to commit yourself to reach v20 before the API is really settled or using a 0.x to communicate "we are regularly breaking things while the API is exercised and settled". I think either is fine, actually; you rapidly get to a point where breaking changes settle down. It more that we have a dislike of "Verion {{some large number}}" that is unwarranted. Rapid release products are breaking that.

I am fine with changing the major version on any breaking change and I would break early and often in the pursuit of the best API. At least at this stage of development. BTW, the removal of `tick` was also a breaking change.

This early I'd prefer to break than to add compatibility bloat, and the best way to communicate that is to increase the breaking-change version indicator.

I've seen one other case that used the rightmost number to signify API level, so that would only change if the API was incompatibly changed, FWIW.

**Comment by yosbelms** [comment]
1. `preffix: "#"` - use hash. History should be triggered in any other case:

`preffix: "#"` hash, routes are leading slash free
`preffix: "#/"` hash, routes with leading slash
`preffix: ""` history, routes are leading slash free
`preffix: "/"` history, routes with leading slash

2. Semver. you can break in a new branch and merge later when more features has come and domvm be ready for a breaking 2.x. I'm sure Mithril rewritting will be an important feed for domvm 2.x.

**Comment by leeoniya** [comment]
@tamasnet 

`prefix: "/"` plus ignoring leading slashes is what i was thinking as well, but then calling it "prefix" is awkward cause sometimes it is and sometimes it isnt. maybe leaving it as `root` is better in this case, but i think either way it's an ambiguity that'll have to exist. keeping `root` will fare better for backwards compat as well.

@lawrence-dol, @yosbelms 

`prefix: ""` is not clear enough to me as implying a history mode toggle, pretty obscure. but in the end this consistency may win out.

> BTW, the removal of tick was also a breaking change.

`tick` was never officially documented, which made its removal easier. It was quite fragile anyhow and the lifecycle hooks are much better for not using it. When using `tick`, you had to wait at minimum `16.666ms x <some tweaked multiple>` for did* hooks to fire and "hope" that a repaint was triggered by then. Now the repaint is triggered by the lib or explicitly by you (via `u.repaint(node)`) and delay times as low as 1ms. It's a huge win in both reliability and perf.

@yosbelms 

> Semver. you can break in a new branch and merge later when more features has come and domvm be ready for a breaking 2.x.

The problem is that 2.x is pretty far out if it were used to accumulate planned breaking changes, because there aren't any major ones on the horizon. I was considering dropping JSONML and going to hyperscript & explicit children arrays but limited internal testing has not revealed major speedups...yet.

**Comment by yosbelms** [comment]
@leeoniya
Could be `root` used in place of `prefix`?
As you use Semver there is no problem releasing 2.x soon. If 2.x is pretty far and you want to add breaking changes in the way you don't want Semver ;-)

**Comment by tamasnet** [comment]
> maybe leaving it as root is better in this case

I think you're right. So basically you'd just be deprecating `useHist` at this point and allowing `root: "/"` as an equivalent.

>  I was considering dropping JSONML

NOOOOOOoooooooo... 😱 I don't know about others but this is the first time I'm using JSONML and it's working really, really well for me.

**Comment by yosbelms** [comment]
I'm with @tamasnet, don't drop JSONML please

**Comment by leeoniya** [comment]
so, i think i'll actually go ahead and add a uniform `prefix`, including `prefix: ""` for history mode. turns out there's no reason to remove useHist/root. internally it's much less risky to simply decompose `prefix` into the existing internal useHist/root flags. I'll probably remove useHist/root from the docs though (thus quasi-deprecating it), but they will continue to work and we can stick with 1.x.

@tamasnet @yosbelms 

> NOOOOOOoooooooo... 😱 I don't know about others but this is the first time I'm using JSONML and it's working really, really well for me.

The main issue with JSONML is that it compels an extra array allocation *per node* in the templates. Whether this has significant perf penalties by forcing GC is not clear but the more I work on improving perf, the more I'm convinced that gains can be had elsewhere.

I have no near-term plans to ditch JSONML and if this ever happens, there will definitely be an adapter provided to retain JSONML templates without any required API changes.

**Comment by lawrence-dol** [comment]
I have no objections to ditching JSONML in favor of hyperscript & explicit children arrays; having gone back recently to my Mithril code, I realize that while JSONML is more compact, it's less clear. I've been trying to get used to JSONML, but my mixed feelings remain. It just presents, rather unexpectedly, as more visually cluttered for anything beyond simple nodes.

Changing my views would be mechanical. I don't have a strong preference, but the `h()` encapsulating an HTML node is really quite clear. And, of course, since I can easily add an `h()` wrapper, it's not a very big deal.

**Comment by leeoniya** [comment]
@lawrence-dol Definitely open a perf issue to investigate if you can reproduce the lag in a test case. A few thousand nodes is a view that could definitely benefit from optimization. Even kivi and Inferno (the fastest libs right now and likely pretty close to the theoretical ceiling) would only reduce your lag 2x compared to domvm [in low mutation scenarios] without app-specific optimizations.

**Comment by lawrence-dol** [comment]
@leeoniya : Of course. I haven't yet, because I haven't had time (priority) to pursue it myself and it's quite possible that the problem is in my data-processing code. Also, from a view complexity point of view, the code is already maximal so the current performance is most likely acceptable for initial release.

So much to do; so little time to do it.

**Comment by lawrence-dol** [comment]
FWIW, I have finally decided to use hyperscript like wrappers, instead of plain JSON ML. Yes it slightly obscures the structure of the resulting tree, but with a simple view it's irrelevant and with a complex view I find it:

  1. Slightly more readable,
  2. There's a very natural transition to using view helpers for subparts of the view which look like they belong without being confusing.

A fair, but still quite simple comparison is:

    return spanBox(1,chc.dspLength+2,".choice",[
        elm("input."+typ, {
            id                          : idx,
            name                        : grp,
            type                        : typ,
            checked                     : valfnc,
            disabled                    : !chc.available,
            tabindex                    : idx,
            onchange                    : chgfnc,
            zIndex                      : Z_CHOICE,
            }),
        elm("label",{ for: idx }, NBS),
        elm("label",{ for: idx }, chc.text),
        ]);

versus:

    return spanBox(1,chc.dspLength+2,".choice",[
        [ "input."+typ, {
            id                          : idx,
            name                        : grp,
            type                        : typ,
            checked                     : valfnc,
            disabled                    : !chc.available,
            tabindex                    : idx,
            onchange                    : chgfnc,
            zIndex                      : Z_CHOICE,
            }, ],
        [ "label",{ for: idx }, NBS      ],
        [ "label",{ for: idx }, chc.text ],
        ]);

**Comment by leeoniya** [comment]
@lawrence-dol 

Sure, i'm not here to convince anyone that JSONML is the final word in html notation (it isnt). However, you should profile to make sure the wrapper doesnt introduce additional overhead (assuming you're using the `arguments` variant shown in the readme, which may may cause de-opt in V8).

**Comment by lawrence-dol** [comment]
> assuming you're using the arguments variant

At the moment, no, I am just using a simple case on arguments.length to build a 1, 2, or 3 length array for elements, and a 1, 2, 3 or 4 length array for components (view functions). I have a separate `elm()` and `cpt()` function.

**Comment by lawrence-dol** [comment]
BTW, for anyone interested, the final wrapper functions I've settled on are:

    // View-model hyperscript element helper for completely uniform templates.
    vElm=function(tag,atr,con) {
        var argcnt=arguments.length;
        if(con==null && typeof(atr)!=="object" || Array.isArray(atr)) { argcnt=3; con=atr; atr=null; } // optional attribute object
        if(argcnt>3) { con=Array.prototype.slice.call(arguments,3); }                               // less efficient, but allows full compatibility with JSONML
        return (arguments.length!=0 ? [tag,atr,con] : null);                                        // return a uniform array!
        };

    // View-model hyperscript component (sub-view) helper for completely uniform templates.
    vCpt=function(vFn,mdl,key,opt) {
        return (arguments.length!=0 ? [vFn,mdl,key,opt] : null);                                    // return a uniform array!
        };

With the slightly more verbose names to make them standout a little more.

**Comment by leeoniya** [comment]
this implementation is complete in https://github.com/leeoniya/domvm-router

Work fine in the v2 ThreaditJS rewrite [1], but needs moar testing.

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/demos/ThreaditJS/app.js#L254
