### ISSUE TITLE
Run tests in a CI/CD + BrowserStack/Saucelabs

### ISSUE THREAD

**Issue by yosbelms** [leeoniya/domvm#85]
Add automated test running on commit or PR will be a great plus for stability and to avoid regressions. Platforms such as BrowserStack allow run tests in different browsers on different OSs, so it bugs should be rapidly identified and fixed eventually.

I recommend TravisCI or CircleCI for CI/CD. I use CircleCI most of the time because automated publishing to npm.js is pretty straightforward.

**Comment by leeoniya** [comment]
I think the issue is not the lack of test-running, but rather an insufficient number of tests.

Things like lifecycle hooks/ensuring things animate properly, routing, simulating some actions in the demos. All that stuff needs to be written first before a CI can be used. At this time adding a CI will not prove to be very useful :/

I would first prefer to dedicate time to increasing test coverage. Opening a few demos and the qunit test page (which runs in 300ms) before tagging a stable release is not huge amount of work. The reasons regressions have been occuring is simply cause more qunit tests must be created.

**Comment by yosbelms** [comment]
>  At this time adding a CI will not prove to be very useful :/

The important thing is not the CI, but Browserstack for **cross browser testing**. Tests are always insufficient, I'm absolutely convinced that it will make `domvm` more reliable.

**Comment by leeoniya** [comment]
> cross browser testing

You can still only automate tests that have already been written. I do run the qunit tests in IE9+, Chrome and FF, though I only manually test the demos in Chrome and sometimes FF since some use ES6/7 features.

Anyways, if you'd like to contribute what's needed to make this happen, I'd appreciate it. I'm currently focused on tweaking the recycling algo so the DOM may be reused from unmounted views [1].

[1] https://github.com/leeoniya/domvm/issues/83#issuecomment-227906693

**Comment by yosbelms** [comment]
I would, but I can't use any paying platform because U.S. restrictions to my country. So, I'm able only to setup a CI but not **cross browser testing platforms** mentioned above.

**Comment by tamasnet** [comment]
@yosbelms Would you be able to use my BrowserStack account? If not directly then at least if you are able to create/maintain the test suite I could provide the runtime environment?

**Comment by yosbelms** [comment]
@tamasnet fine, give me time to find a proper setup, y will poke you back in this threat

**Comment by leeoniya** [comment]
On the topic of testing, I have a few thoughts.

1. How/would the workflow for change? I assume pushing to Github and the post-recieve hooks poke the CI? Assuming this is true, this would be insufficient to eliminate the current local test running.
2. I dev on Windows, so if the CI tells me something now fails on Safari/OSX or some mobile device, I have no good way to act on this feedback. I realize that it's no much different than just being blissfully ignorant of the facts, but thought I'd bring this point up.
3. Local test running could be automated perhaps with Selenium, but I don't know with what frequency I would want to run it (since not all browsers can run headless, plus PhantomJS's webkit is really old)

I still think that a CI will not add much until at least the manually-tested demos have written acceptance tests. My concern being that a CI at this point may complicate the workflow for little value and provide non-actionable feedback and will offer little over a local, instant-feedback Selenium setup with no external SaaS deps.

However, I this is something that will help you contribute additional tests, then I'm all for it.

Just thinking out loud, pay no special attention :)

**Comment by yosbelms** [comment]
@tamasnet, @leeoniya, I already know the details to setup CircleCI+Browserstack. However @leeoniya has its own workflow, I'm not sure if a workflow change will add any benefit regarding there is just on developer in the team ;)

I closed it to remove noise from priorities. @leeoniya if you want to do some experimenting about this don't hesitate to contact me.

**Comment by leeoniya** [comment]
@yosbelms thanks, i definitely will.

I periodically check in with the whole tooling ecosystem to see if anything looks like it may be worth using for my projects.

https://github.com/tivac/es6-watching (rollup & buble) is very simple, small and works well, so I've been considering migrating to es6 (maybe minus require/modules, cause it would make domvm unusable without building even in modern browsers, but may result in smaller bundles). In that case I would also add automation for Closure concat & min. Typescript is here to stay it seems, but domvm it too small to benefit much from it. Webpack & jspm are also on the radar, as long as they're still around in 6 months.

**Comment by grumpi** [comment]
> Typescript is here to stay it seems, but domvm it too small to benefit much from it.

I haven't tested Typescript with domvm yet (only with mithril at some point). In my mind, currently, the appeal of Typescript is to typecheck my templates so I don't do stupid things like use a string in a list of elements (I did run into this kind of error a bunch of times when porting my templates to 2.x-dev; it wasn't a big deal, but it got me thinking how to prevent it in the future).

There is value even just in having (checked) type signatures. They are a valuable piece of documentation.

**Comment by leeoniya** [comment]
Typescript 1.0 had pretty poor typeguard recognition which made it annoying to use for purposes with a few variable signatures. I think 2.0 is much better.

I actually started the 2.0 rewrite in typescript to try it out but quickly became annoyed that it would not allow loose checking of things like `foo == null` which is a terse, fats and reliable test for only `undefined` or `null`. It also wanted me to coerce all values to strings befor assigning them to `.textContent`, which seems pointless since the browsers will do this automatically and doing so just to please the compiler can hurt perf by doing extra unnecessary work.

I'll have to re-evaluate at some point, though. The code is much better structured in 2.0 to make the porting experience better.

**Comment by grumpi** [comment]
Ah, having to coerce values unnecessarily does seem rather annoying.

I suppose a good way to work with Typescript for now is to just use some lightweight non-checked type signatures for the template functions - in "app-land", not in domvm itself.
