### ISSUE TITLE
Drop SVG and MathML support

### ISSUE THREAD

**Issue by yosbelms** [leeoniya/domvm#86]
Domvm is a great library for composing views with standard `dom`. There is many libraries specialised in SVG out there, e.g D3. I don't think any one is going to use `domvm` for SVG or MathML(not supported by Chrome).

My proposal is to drop the SVG and MathML support, it will make `domvm` faster for sure, less code noise, focused etc. What do you think about it @leeoniya?

**Comment by leeoniya** [comment]
Probably true, especially for MathML. I'm fairly confident this will not impact performance in a measurable way. There is also not a lot of extra code in there that handles these cases (< 200 bytes). I'll consider this for 2.0, but it's not a priority.

**Comment by leeoniya** [comment]
been doing some work recently that has me leaning towards keeping SVG support for cases like this:

https://codepen.io/dudleystorey/pen/DcBIH

**Comment by explorigin** [comment]
I would recommend keeping SVG. It's use is likely to increase a lot when FontAwesome releases their SVG icons from the Kickstarter campaign.

**Comment by leeoniya** [comment]
@explorigin 

There is a case for SVG support, but icons are not it. Why? Because you can already inject any external dom elements into a vdom template. There is no benefit to actually create them via a virtual dom, in fact there is a penalty. If you want to mutate *parts* of the icon, like change colors or animate, then perhaps. But you're better off doing more complex svg stuff via http://snapsvg.io/, https://two.js.org/, http://anime-js.com/ etc.

I've actually been working with SVG icons (converted from font-awesome via by https://icomoon.io/) and how I handle it is to simply have them already present in the html (maybe in a `<template id="icons">`) then `mySvgIcon.cloneNode(true)` and inject that into the a domvm template. Here's an example:

https://jsfiddle.net/b2y6ccj3/

Why would you ever want to define that static SVG icon in a virtual dom structure? You wouldn't.

Now, if your *entire app* is SVG, including layout, etc. That would be a valid case for adding SVG back into domvm. The current v2.0.0 does not have SVG support.

**Comment by explorigin** [comment]
OK that makes more sense.

**Comment by lawrence-dol** [comment]
@leeoniya 

That's really quite elegant. You should include that example somewhere in the detailed documents or a code reference.

I could utilize that, having just included the FontAwesome file just to get a half dozen icons, specifically because they are scalable (though with the full intention of leveraging them elsewhere in the wider app over time).

**Comment by leeoniya** [comment]
@lawrence-dol 

I recently configured a brand new, fully-updated Debian unstable Linode VPS with 2 cores, and set up all HTTP2 & nginx cipher configs to get A+ in https://www.ssllabs.com/ssltest/

Do you know how much time it takes to simply negotiate the initial TLS1.2 connection w/2048 bit keys? **~1000ms** - that's before any content can be served by the nginx. After that, it takes an additional 250ms to get to full page load (just 2 requests of 1.4KB html and 40.1KB logo). That's **1.25 seconds** for a landing page with practically no content. Every reload after that with cache disabled (in devtools) ~140ms and ~67ms with cache. There is no way I want to add any more overhead to an initial page load by including webfonts and icon fonts which will delay showing any text *at all* until the fonts download.

You can aid this by embedding the fonts via data URIs and base64 encoding them [1], but for my own projects, unless absolutely necessary, I'm moving from icon fonts to SVG icons and from WebFonts to system fonts à la [3]:

`font-family: -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif;`

[1] https://www.filamentgroup.com/lab/font-loading.html
[2] https://news.ycombinator.com/item?id=12865998
[3] https://medium.design/system-shock-6b1dc6d6596f

**Comment by leeoniya** [comment]
gonna close this. if another issue needs to be made regarding SVG, it'll be the inverse of this one 😆

**Comment by leeoniya** [comment]
eh, i dunno. SVG doesnt take much additional code to support [1]. i created a `defineSvgElement` branch. here's a demo [1].

i'm mostly worried about various SVG-ism bugs emerging and having to then maintain all the slight differences from a normal dom api all over the codebase. though much of it can probably be contained to `dom.js`. in v1 it would have been much more dispersed.

[1] https://github.com/leeoniya/domvm/commit/d13d138d736063170df111493eceeb2d246900f4
[2] https://rawgit.com/leeoniya/domvm/defineSvgElement/demos/svg.html

**Comment by lawrence-dol** [comment]
I know this is old, and closed, but just a heads up that I now have support for assembling SVG files on-demand, and will be switching to using SVG icons entirely if I can figure out how to deal with setting the default/main SVG stroke color. I'm glad this support was left in.
