### ISSUE TITLE
Does the view-model's key belong with the declaration, or in the view-model?

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#87]
As I work through #83, adding/removing the component's key, I notice a discontinuity. Each test with and without a key has me adding or commenting out the key based on changes made in the view itself.

It then occurs to me, at least in this particular case, it's they view-model which has the knowledge of whether this view needs to be re-initialized whenever the model changes, not the container.

This suggests that the key should be a property of the view-model, not of the parent node.

Thoughts?

**Comment by leeoniya** [comment]
> This suggests that the key should be a property of the view-model, not of the parent node.

This *is* the way it works, so I'm not sure what you mean. It's the parent, though that's responsible for checking its old body against its new body to see which views are still present, reordered, or need new models passed down. The views themselves cannot do this, right?

Could you provide some code to clarify?

**Comment by leeoniya** [comment]
The view can in fact set its own key, but it can only do so from the template's root node (css id or _key becomes the view key). But this will not work the way you expect because the view's identity must be externally defined as this is necessary to match the vm (in the old tree) to the view declaration from you returned template. this is the way the state transfers, the parent must match an existing vm in the old vtrer to some identity present in the new template. that's the nature of declarative construction.

if you inject a pre-init vm on each render, then it does not need to be disambiguated since it is literally present in old and new vtrees and can be reconciled.

**Comment by lawrence-dol** [comment]
Gotcha.
