### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parentNode' of null view.js:302

### ISSUE THREAD

**Issue by shasderias** [leeoniya/domvm#89]
The following view snippet returns the following error:

```js
 function View(vm, deps) {
      return function () {
        var app    = deps.app;
        var router = deps.router;

        if (app.issues == null) {
          return ["h3", "Loading..."];
        }

        var issue  = app.issues[app.selected];

        return [".container",
          [".row", [".col-md-12",
            ["h3", "Hello World"],
          ]],
        ];
    }
}
```
Uncaught TypeError: Cannot read property 'parentNode' of null view.js:302 is returned.

However, the following view snippet works fine:

```js
 function View(vm, deps) {
    return function () {
        var app    = deps.app;
        var router = deps.router;

        if (app.issues == null) {
          return ["h3", "Loading..."];
        }

        var issue  = app.issues[app.selected];

        return ["h3", // change ".container" to "h3" 
          [".row", [".col-md-12",
            ["h3", "Hello World"],
          ]],
        ];
    }
}
```

As does the following view snippet:

```js
function View(vm, deps) {
      return function () {
        return [".container",
          [".row", [".col-md-12",
            ["h3", "Hello World"],
          ]],
        ];
    }
}
```

Am I doing something wrong here or is this a bug with domvm? I'm on the latest commit for branch 1.x-dev.

**Comment by leeoniya** [comment]
Sounds like a bug with root node replacement where `h3` is swapped for `.container`. However, there's already a test for the simple case of this which passes [1]. I'll look into this later today.

For the time being, just return one of:

```js
[".container",
  ["h3", "Loading..."]
]
```

and

```js
[".container",
  [".row", [".col-md-12",
    ["h3", "Hello World"],
  ]],
];
```

[1] https://github.com/leeoniya/domvm/blob/1.x-dev/test/tests.js#L409-L427

**Comment by leeoniya** [comment]
related: #84

**Comment by leeoniya** [comment]
i am unable to reproduce :/

could you post a fiddle that exhibits the error? the following works ok for me:

```html
<!doctype html>
<html>
	<head>
		<title>domvm bug 89</title>
	</head>
	<body>
		<script src="../src/domvm.js"></script>
		<script src="../src/utils.js"></script>
		<script src="../src/view.js"></script>
		<script src="../src/route.js"></script>
		<script src="../src/watch.js"></script>
		<script src="../src/html.js"></script>

		<script>
			var issues = false;

			function View(vm) {
				return function () {
					if (!issues)
						return ["h3", "Loading..."];

					return [".container",
						[".row", [".col-md-12",
							["h3", "Hello World"],
						]],
					];
				}
			}

			var vm = domvm.view(View).mount(document.body);

			setTimeout(function() {
				issues = true;
				vm.redraw();
			}, 2000);
		</script>
	</body>
</html>
```

**Comment by shasderias** [comment]
Sorry, I probably did not provide enough info in my first post. Also, extracting a failing test case took some time.

Anyhow, https://jsfiddle.net/fg2Lpzku/ 

Replacing line 31 with your suggested interim fix (i.e. return [".container", "Loading..."]) makes the snippet work.

**Comment by shasderias** [comment]
https://jsfiddle.net/jL9d02y4/2/

More succinct failing case?

**Comment by leeoniya** [comment]
ah, i suspected it might be something like this. root node replacement is somewhat umm...half-baked [1]. It was never really vetted for complex sub-trees or intended for replacing sub-view hierarchies. The main use-case I had in mind was switching an active link in a nav menu from `a` to `span`, or displaying either simple error in place of another simple template. I was quite iffy about supporting it in the first place.

There's a good chance that some cleanup pass is not being properly done during vnode allocation or freeing. I'll take a look to see if this could be a simple fix. Keep in mind though that when you're using explicitly instantiated sub-vms there could be situations when something goes weird because domvm has no way to throw away the vm you hand it (and hold references to), eg. operating on an unmounted vm may result in undefined behavior, mem leaks, etc.

[1] https://github.com/leeoniya/domvm/blob/1.x-dev/src/view.js#L326-L331

**Comment by leeoniya** [comment]
ok, something is broken with sub-vm rendering here. which is serious. gonna track via #91

**Comment by leeoniya** [comment]
alright, i'm blind, stupid, or both. you have your dependencies inverted. when you init each vm, its children/dependencies must exist already. maybe it's just a shortage of coffee today. this works fine:

```js
this.detailvm = domvm.view(DetailView, this);
this.vm = domvm.view(View, this);
```

**Comment by lawrence-dol** [comment]
This is one of those areas where an inline invocation of `redraw` is what's tripping things up and is surprising. This is a very subtle trap, and unexpected during set up because, "of course nothing is going to be rendered, I haven't even mounted the main view yet". Nonetheless the render function is invoked and hits a null value.

I missed this error too, since instantiating the main view followed by it's sub-views is a perfectly natural thing to do.

**Comment by lawrence-dol** [comment]
For what it's worth, and for wider context, a similar problem plagues graphics rendering frameworks. Since the framework is usually agnostic of the rendering "surface", certain things, like render extents, can't be calculated until it associated with the underlying graphics rendering context. So one cannot calculate things like the bounds of a piece of text until after you've "mounted" the component, but ideally, layout would be calculate before you do that. Hence, a good system must be designed to calculate layout as part of rendering even though the layout is usually fixed for a given panel unless the bounding window is resized.

**Comment by shasderias** [comment]
Does this mean that if I have the following lines in my code, it is causing me to hit said "bug"?

```
self.vm = domvm.view(View, { app: self.app, router: self.router });
self.detail.vm = domvm.view(DetailView, { app: self.app, router: self.router });
```

And further to that, if I reverse the order of said lines, the "bug" should not occur? If thats the case, please hold, I've reversed said lines, and I'm still encountering the error. :P I'll take a look and try to come up with another jsfiddle.

**Comment by leeoniya** [comment]
when this example is arranged in standard imperative dep-first order and removing the immediate post-mount redraw, everything works fine [1].

```js
  this.posts = [1, 2];
  this.selected = null;

  this.detailvm = domvm.view(DetailView, this);
  this.vm = domvm.view(View, this);
```

@lawrence-dol 

yeah i'll need to look into delaying render calls at least until mount() but it's rather tricky because the template returned by render can itself define the key of the view by which it's externally identified which is needed when embedding in third party wrapping components. i would have to abandon the ability to identify views by their template root's `#id`, `_key`. this may be possible but it would definitely break tests and probably cannot happen in 1.x.

[1] https://jsfiddle.net/fg2Lpzku/2/

**Comment by shasderias** [comment]
Still running into the error in actual code, although in actual code, the instantiation of the vm is done in an init function (to dep inject the router). Should I continue digging or is this user error?

**Comment by leeoniya** [comment]
@shasderias try making the changes recommendedso far and keep digging, please. by digging i mean dont try to fix it yourself, just post the failing code.

in the mean time, i will try to see if lazy render() invocation can be done, i thonk it might be possible without much breakage.

regarding router dep-injection, i've recently started advising against it. both the top level app and router are singletons. trying to pass the router down through your view heirarchy for the sake of purity is not practical and leads to awkward wiring and code flow :/

**Comment by shasderias** [comment]
I've already made the recommended changes and its still failing. Will clean up the code and post it.

**Comment by lawrence-dol** [comment]
> regarding router dep-injection, i've recently started advising against it. ... leads to awkward wiring and code flow.

Oh, good; that was my feeling too.

**Comment by shasderias** [comment]
https://jsfiddle.net/xh5djsup/

**Comment by lawrence-dol** [comment]
> i would have to abandon the ability to identify views by their template root's `#id`, `_key`.

Hmmm. A hard pill to swallow. Perhaps mitigated by using a light component wrapper around such things such that the parent can declare the key? A simple wrapping `div` would most oft be a small price to pay.

**Comment by leeoniya** [comment]
should be fixed now. lemme know how it goes.

**Comment by shasderias** [comment]
works great, thank you

**Comment by leeoniya** [comment]
@lawrence-dol @shasderias @yosbelms 

https://github.com/leeoniya/domvm/commit/744d8c5020a63bf7c02fb62f64abcf6f616ca7c6 implements lazy rendering. you can now define imperative views / vars out of order.

the only minor change is to SSR isomorphism. since there is no render invoked and no vtree built during view init, you have to call `mount()` with an empty target to force render() and be able to use `domvm.html()` on it.
