### ISSUE TITLE
SSR

### ISSUE THREAD

**Issue by leon-andria** [leeoniya/domvm#96]
In the sample below https://github.com/leeoniya/domvm#isomorphism-html-attach, i think it misses some piece of code to make it running.
// on the backend
var vm = domvm.view(SomeView, someModel);
vm.mount();
// have server barf this html into the returned document
var html = domvm.html(vm.node);

1. We should mount
2. We pass the node property for the vm

Let's me know if I can make a pull request to update the documentation, it will helpful for the other readers.

**Comment by leeoniya** [comment]
thanks @leon-andria,

this may be a case where the docs are in sync with the `1.x-dev` branch, but not in sync with the published stable/npm version.

the latest stable version included a lazy rendering commit [1] that required an empty `mount()` call to the view to build out the vtree. the docs were updated to reflect this but afterwards there was another commit that restored the original behavior by calling `mount()` implicitly and reverting the doc changes, see [2].

this was BC/semver fail on my part since node/npm is kind of a second-class-citizen as the lib is primarily aimed for browser usage. i don't have any insight into how many people use the SSR aspects of domvm, but it looks like more than 0 ;)

Can you try it with `1.x-dev` and see if it works as documented?

[1] https://github.com/leeoniya/domvm/commit/00d5db4127e3fd0603eae9ec365cceccc18c8e2c
[2] https://github.com/leeoniya/domvm/issues/92

**Comment by devmondo** [comment]
hey @leeoniya 

thanks a lot for your fast response , add me as another one who is using SSR :)

**Comment by leon-andria** [comment]
hi @leeoniya,

I would to confirm that with the branch 1.x-dev, the documentation is sync.
However, it should be great to easily make a npm install on the branch with a correct versionning.

Making npm install git:\github.com\leeoniya\domvm.git#0c3a3b8 give a invalid version 1;x-dev

The SSR is really important and we use it a LOT :-)

**Comment by leeoniya** [comment]
i was hoping to merge a few more fixes/optims before tagging 1.2.10, but it seems prudent to let 1.2.10 be an ssr-unfooing version. i'll have it tagged and published later today.

**Comment by leon-andria** [comment]
Awesome, thank you @leeoniya 
Keep you update for any feedbacks

**Comment by leeoniya** [comment]
1.2.10 is up/published

**Comment by yosbelms** [comment]
> since node/npm is kind of a second-class-citizen as the lib is primarily aimed for browser usage

Most of the developers uses npm as main package manager nowday regardless if they are using nodejs for server-side or not. Many library authors adopted npm as an important channel of distribution due to the popularity of npm, example, jQuery, Angular, React, Bootstrap. None of them for server-side.
